---
title: "Resumen del Encuentro Latinoamericano de Varones Antipatriarcales"
date: "2017-10-11"
categories:  
  - masculinidades
---

> Resumen de lo que fue el [Encuentro Latinoamericano de Varones Antipatriarcales, ELVA](https://bastimapache.cl/posts/2017/2017-10-07-encuentro-latinoamericano-varones-antipatriarcales-elva/), llevado a cabo en Chile

Nunca me había sentido cómodo junto a otros hombres, siento que aprendí caleta. Un grupo reducido de compas lo levantaron a pulso, así que hubieron ciertas deficiencias logísticas, pero el ambiente, el contenido y la energía compensaron con creces. La asstencia fue como de un poco más de 100 personas, y el lunes bajó como a 60. Habían muchísimos compes argentinos que se quedaron los tres días, así que muy rico compartir con ellxs y conocer sus experiencias (el acento se pega al tiro, jaja). Hubo poca asistencia trans, pero les que fueron participaron harto y tuvieron harta voz en las plenarias, charlas y micrófonos abiertos. 

Eran muchos talleres de temas diversos, la mayoría con énfasis en el cuerpo. Se daban simultáneos y por bloques, uno se anotaba y asistía. Yo fui a uno de paternidad, y al de contact y escritura que organizó la asamblea. El lunes expuse en la mesa de experiencias organizativas junto al partido piquetero, Traidores de papá (argentina), otro colectivo que no me acuerdo (argentino igual), y dos individualidades trans. También la Asamblea tuvo un puesto de [nuestro fanzine](/posts/2017/fanzine-pensar-masculinidades-criticas/) y vendimos los 50 que confeccionamos.

Habían hartas instancias de dinámicas grupales y místicas, así que siempre se incentivó la participación desde el contacto y el desafío de ciertas falencias masculinas, como el cuidado de personas, y la afectividad. También hubieron varias plenarias abiertas o en grupos, en una grupal hablamos de cuidados, y luego discutimos como reaccionar ante violencia machista (en base a preguntas que nos entregaron colectivos feministas), y lo expusimos mediante obras de teatro jiji. 

En la plenaria final se hicieron evaluaciones y autocríticas, y se discutió ene un caso de que le prohibieron la entrada a 3 mujeres cis que fueron a ver una performance. El argumento fue que era en la noche y había copete, entonces era para evitar situaciones de acoso o violencia. Se debatió sobre el carácter separatista, y en general se rechazó que se hayan expulsado (en todo caso se fueron en buenas al parecer, se conversó con ellas y todo eso). 

Y bueno, eso, fue una experiencia demasiado rica para problematizarnos, formarnos, y desafiarnos al cambio. Siento que en Chile igual la lucha antipatriarcal desde identidades masculinas está en pañales. Como que falta mucha concientización en los compas de izquierda, no le llegamos ni a los talones a lo que han trabajado al otro lado de la cordillera.