---
title: "La educación como herramienta de inclusión de género"
subtitle: "Ensayo para el ramo de Iglesia y Derechos Humanos en Latinoamérica"
date: "2015-11-24"
categories:
  - "sociología"
tags: 
  - género
  - educación
  - derechos humanos
format: html
---


Probablemente una de las formas más eficientes de combatir cualquier forma de oposición discursiva es mediante su eliminación directa. Si bien esto puede ser entendido como una operación ofensiva (el obrar directamente en pos de la eliminación de una idea, una persona, o una institución), bien puede también tratarse de un ejercicio por omisión: desde una posición enunciativa privilegiada, la no-representación de un otro (por ejemplo, la omisión de incluir, o la omisión de considerar la existencia de un otro) bien puede significar la imposibilidad de existencia legitimada para este otro. Este último caso es el que suele afectar comúnmente a las tendencias progresistas, entendidas como aquellas que cambian el entendimiento establecido; o bien a las de vanguardia, es decir, aquellas que se sitúan en la delantera de la actualización del conocimiento.

El tema de la discriminación de género ha sido un punto que académicamente ha venido tratándose desde mitades del siglo pasado, pero que sólo ha encontrado un aterrizaje en lo práctico y político en las últimas décadas; pero en continuación con dicha línea de estudio, los problemas sociales vinculados a la diversidad sexual y la identidad de género son bastante más recientes, recibiendo una recepción social amplia en nuestro país quizás apenas en la última década.

Chile se ha adscrito a numerosos tratados internacionales bajo la temática del combate a la discriminación en sus diversas formas. Particularmente, tratados como el de la ONU sobre diversidad sexual e identidad de género en 2011 y el de los Principios de Yogyakarta en 2006, o el de la OEA en 2008 con declaraciones sobre la temática, son algunos de ellos, que desde el año 2009 son anexados al cuerpo constitucional chileno como principios para sus políticas futuras.

El objetivo de estas nuevas políticas es instar a que los Estados tomen posturas para erradicar cualquier forma de discriminación a través de legislación, administración, y educación en pos de un cambio en el sentido común de la población. Es que el advenimiento de los movimientos feministas, el estudio del género, y la secularización general de la población han abierto el espacio para visibilizar nuevas formas de interpretar las relaciones interpersonales e institucionales entre los géneros, y una diferente concepción de la sexualidad y la identidad posibles para los individuos, dando lugar a mayores libertades en las constituciones del yo, fuera de la tradicional concepción dicotómica del género, y heteronormativa de la orientación sexual.

En otras palabras, de lo que se trata es de un movimiento de visibilización y reconocimiento de formas de ser que antes eran sancionadas o bien silenciadas de los espacios de representación y agencia política, posibilitando una participación legitimada de dichos actores en espacios públicos. para estos fines, la educación toma un rol preponderante, ya que, en tanto “progresistas”, estas posibilidades humanas deben ser introducidas al campo social de una forma propicia, que combata la resistencia que se pueda encontrar, generando un espacio seguro para el desarrollo de estos individuos que llegan a romper con las viejas estructuras de género.

El 2012 se promulga el primer mecanismo judicial contra la discriminación arbitraria (UDP, 2015, p. 257), la Ley Zamudio, reconocida por su hincapié en los nuevos delitos de discriminación por identidad de género y orientación sexual. Herramientas como ésta permiten que los individuos bajo situaciones de discriminación puedan verse respaldados institucionalmente y responder contra tales actos opresivos. Si bien la tematización de este tipo de discriminación como punible puede considerarse un avance bajo los conceptos del derecho, es necesario entender que se manifiesta como un síntoma de una problemática social bajo la cual nuestra sociedad está poniendo el ojo, y de ninguna manera puede considerarse que la promulgación de una ley es una solución definitiva. Bien lo dijo Luis Larraín, presidente de la Fundación Iguales:
> (la ley es) “poco útil en la práctica”, ya que la discriminación es un problema histórico y endémico de la sociedad, que no se resuelve con respuestas puntuales, sino con medidas estructurales como la revisión de los currículos educativos del Mineduc, y de las mallas de ciertas carreras; con campañas masivas orientadas a quienes ya no están en el sistema educacional; y la capacitación a funcionarios del Estado. (Ibíd, p. 258)

Así, entendemos que las leyes no pueden ser propuestas como solución a problemas estructurales, por lo que en este eje son aún necesarios otros avances. La orientación del texto es, en este sentido, apelar a la necesidad imperante de adherir a los currículos estudiantiles los temas de la disidencia sexual y la desigualdad de género, con el objetivo de empezar un recambio generacional acerca de la temática que nos entregue, en un futuro, mujeres y hombres removidos de prejuicio contra sus pares que viven o adoptan de diferente manera.

La educación, entonces, puede ser la herramienta que permita visibilizar la identidad de género y la orientación sexual, combatiendo la discriminación desde su origen: el prejuicio, la ignorancia, pero principalmente el acto de naturalización y universalización de hechos sociales, como es la heteronormatividad.

Las autoras del texto llevan a cabo una investigación acerca de documentos relacionados al ámbito legal y la educación que toquen los temas sobre identidad de género y diversidad sexual. Revisan las orientaciones del Ministerio de Educación, los currículos escolares para las asignaturas de Ciencias Naturales y Orientación, las bases formativas de las carreras de Educación Parvularia, Pedagogía Básica, Pedagogía Media y Educación Diferencial, y contenidos web del Ministerio de Educación y de la Superintendencia de Educación. Las conclusiones que obtienen alertan sobre la invisibilización del concepto de identidad sexual, orientación sexual, e identidad de género en los programas escolares de ciencias naturales (Ibíd, p. 260); mientras que en el programa de a asignatura de orientación, “impresiona la total ausencia de contenidos orientados al reconocimiento de la identidad de género y la orientación sexual” (Ibíd, p. 261). A pesar de aquello, se identifica la existencia de material de apoyo sobre diversidad sexual para los establecimientos y docentes. En lo que respecta a las carreras docentes, destaca la invisibilización de las temáticas (Ibíd, p. 275).

La carencia de un programa fuerte que proponga las temáticas de la desigualdad de género, identidad de género, y diversidad sexual en las instituciones que forman a las y los profesores y profesionales del futuro es problemático. ¿Cómo podemos llegar a la representación de minorías y su respeto como iguales si éstas no son visibilizadas, y los prejuicios al rededor de ellas no son combatidos a nivel societal? 

Momentos como el actual son claves, donde diferentes factores se han aunado para entregar mayor poder de voz y exposición a diferentes grupos sociales, lo cual claramente conlleva reacción por parte de los demás, sintiéndose atentados por la aparición de un otro diferente, nuevo, que rompe con los esquemas de la normalidad. 

La discriminación oculta la condición de constructo social que tiene la diferencia, al hacerla pasar como si fuese natural. Consideramos necesarias campañas de alto alcance que informen a los ciudadanos acerca de los cambios que vivimos como sociedad, desnaturalizando los prejuicios que transforman a las y los divergentes en sujetos de burla, deshonor y humillación, y elevarlos a una condición de igualdad a través del conocimiento, el respeto, y la libertad.

> Universidad Alberto Hurtado. Centro Ignaciano Universitario. Curso de Formación General Teológica. Iglesia y derechos humanos en Latinoamérica

> Profesor: Boris Hau