---
title: "El tramado detrás de la Obra: Modernidad y diacronía en el Opus Dei"
subtitle: "Ensayo grupal para el ramo de Religión y Modernidad"
date: "2015-06-07"
author: "Felipe Larenas, Jacobo Matheu, Sebastián Muñoz, Bastián Olea"
categories: 
  - "sociología"
tags: 
  - religión
format: html
---

El 26 de Junio de 1975, fallece de un infarto al miocardio monseñor Escrivá de Balaguer. Desde aquel suceso, algunos padres que seguían el legado de Escrivá buscaron las causas para nombrarlo santo. Es en febrero de 1981 cuando la Congregación para la Doctrina de la Fe y de la Congregación para la Causa de los Santos, procede a hacer oficial el decreto que hace mención a la beatificación y canonización de Josemaría Escrivá de Balaguer, sin embargo es desde 1990 que empieza a hacerse efectiva.  Desde este suceso, las puertas para hacer posible el proceso de beatificación marcharon a una rapidez nunca antes vista en el vaticano, es en este mismo año que el papa Juan Pablo II permite incorporar causas de milagros al monseñor, anticipando una pronta beatificación. 

Un año más tarde, Juan Pablo II decretó el carácter milagroso de una curación realizada por Escrivá de Balaguer ante cardenales y obispos. Esta fase es de suma importancia en la causa de Escrivá de Balaguer, la cual concluye el 17 de Mayo de 1992 en la plaza de San Pedro frente a más de 95.000 personas procedentes de todo el mundo. 

La inusitada rapidez que se observó en la beatificación de Balaguer hace que se cuestione si el proceso ha sido manipulado como también el sentido que buscan sus fieles en la canonización de monseñor lo antes posible. Ante estos antecedentes polémicos es que la investigación cobra forma, ya que por estos motivos se han levantado fuertes debates, las cuales enmarcan este análisis.

En virtud de lo anterior, el presente informe tiene como finalidad dar a conocer los ejes que guiarán la futura investigación sobre el Opus Dei. En primer lugar es pertinente dar a conocer el contexto en el cual se engendra la Obra, para así dar paso a su estudio en tanto fenómeno religioso, para ello se recurrirá a los conceptos propuestos por el filósofo Marshall Berman (1986); dando principal distinción a un elemento que se da en la tercera fase de la modernidad, que para fines prácticos de esta investigación se denominará como ethos económico moderno.

Será un eje principal el cómo este ethos mantiene relación con ciertas concepciones morales que tienen un sentido tradicional dentro del Opus Dei, y con la resignificación de este calificativo temporal: la tradición. Es así como estos dos conceptos articularán la investigación, asistidos de una discusión respecto de la ubicación en el tiempo socialmente percibido del Opus Dei a partir de la discusión de los conceptos de sincronía y diacronía. En consiguiente se presentará la pregunta que guiará y dará curso a esta investigación, a su vez se dan a conocer los objetivos generales y específicos que esta investigación pretende desarrollar.

Para tales efectos se generará un marco teórico que abordará los conceptos claves que circularán por la investigación; utilizando la lógica de inmovilidad social que proviene de Calvino, pasando por la ética que se encuentra detrás de la creencia religiosa a manos de Weber, para así redondear los conceptos señalados con las ideas que brinda Marshall Berman, interpretados a través de la aplicación de los conceptos de diacronía y sincronía, que ven su génesis en el célebre análisis lingüístico de Ferdinand de Saussure, y su posterior uso en el análisis de la ideología de Ernst Bloch y en la filosofía fenomenológica de Emmanuel Levinas.

Por lo tanto, es el análisis y exploración del Opus Dei en cuanto este se vincula en una contradicción entre lo tradicional y el ethos económico moderno. Lo anterior es bajo la lupa teórica dada por los estudios realizados en estas áreas, lo cual llevará a presentar las principales conclusiones de este informe a una temática que, al parecer, ha sido poco abordada.

## Contextualización

Los primeros atisbos de la configuración del Opus Dei surgieron en octubre de 1928, instancia en que, según Josemaría Escrivá de Balaguer (fundador), fue el minuto en que tuvo un nuevo contacto con Dios, que lo llevó a comprender cuál era su misión en la tierra. Tal como  recoge María Oliva Mönckeberg (2004), en una investigación sobre el tema, el propio sujeto recuerda que: "Recibí la iluminación sobre toda la Obra, mientras leía aquellos papeles [apuntes sobre las nociones que él había recibido de Dios en los últimos años]. Conmovido me arrodillé (…), di gracias al Señor, y recuerdo con emoción el tocar de las campanas de la parroquia de Nuestra Señora de los Ángeles"  (Escrivá, 1931, citado Mönckeberg, 2004:71).

El fundador de lo que se puede reconocer como el ala más conservadora de la Iglesia Católica es Josemaría Escrivá de Balaguer, monseñor español que fue canonizado en 2002 por el Papa Juan Pablo II. Desde los inicios del Opus Dei, esta vertiente se configuró –según Emilio J. Corbiére (2002)– como una organización vertical fuertemente jerarquizada, donde se ubicaba en la cima "el Padre"; líder máximo idolatrado por todos sus seguidores. Cada uno de sus seguidores debía cumplir una serie de obligaciones de acuerdo a la posición que ostentan dentro de la orgánica. Como bien menciona Emilio J. Corbiére (2002), existirían cuatro grados en que los seguidores se podían asociar al Opus Dei, estos son:

1.	Numerarios: Hombres célibes con estudios equivalentes a doctorado. Se perfeccionan por varios años (5 a 6 años) en teología, para una vez concluidos sus estudios, realizar votos perpetuos de pobreza, castidad y obediencia a la orden. Pueden ser ordenados sacerdotes, sin embargo, siguen ejerciendo la profesión que estudiaron
2.	Agregados: No necesariamente tienen estudios universitarios. Mantienen el celibato y reciben formación teológica. Su vida gira en torno a la consagración de la Obra.
3.	Supernumemarios: Contraen votos compatibles con las leyes del Estado (se casan). No tienen la obligación de dedicar tiempo a la Obra.
4.	Cooperadores: No pronuncian votos alguno con el Opus Dei, pero se reconocen como simpatizantes. Realizan aportes monetarios.

Se suma a lo anterior la existencia de tres ramas fundamentales que conforman al Opus. La primera está compuesta por los sacerdotes de la Obra, la segunda por la rama masculina y la tercera, por la femenina. Esta última está a cargo del servicio de los otros miembros (hombres), incluyéndose las tareas de domésticas donde residen sus asociados (Corbiére 2002).

Ahora, en términos de los preceptos que desarrolla el Opus Dei, se destaca la importancia que significa el seguir un tipo de comportamiento determinado que conduzca al camino de santificación; acontecimiento que todos los miembros de la Obra buscarían con ahínco. El libro donde se registran los principales elementos que deben regir su vida es "Camino" (1939), texto que presenta 999 postulados a los que se comprometen a seguir los miembros de la Obra, para tener la posibilidad de ascender al camino de la perfección. En aquel libro, de acuerdo a uno de los principales estudiosos de la congregación,  se establecen "tres etapas que un socio de la Obra de Dios recorrerá en el camino de la perfección: «Que busques a Cristo: Que encuentres a Cristo: Que ames a Cristo»” (Ynfante 1996:167). María Olivia Mönckeberg (2004) también concuerda con la relevancia que tiene esta obra en los miembros del Opus Dei, por lo que se aproxima al texto a través del reconocimiento de sus principales postulados. De acuerdo a la investigadora existirían ciertos elementos claves en el texto, entre los que se destacan: la supremacía de los sacerdotes por sobre los laicos; la necesidad de contar y desarrollar el "plan de vida" (leitmotiv que guía todas las acciones); la santa intransigencia y santa coacción (intransigencia para defender la doctrina y coacción para intentar llevar a otros); la santa pureza (restricción de las relaciones sexuales al matrimonio); y la indispensable obediencia a los superiores a quienes no pueden criticar ni contradecir.

Los componentes centrales que están inmersos en los principios del Opus Dei dan pie para comprender a la institución como una que aprehende el comportamiento individual de un modo tradicional, asociado directamente al control de los cuerpos y de las decisiones individuales; los miembros de la congregación deben regir sus decisiones a la aceptación de lo ordenado por superiores y la vida sexual está limitada a la concepción, por solo mencionar algunos ejemplos. Precisamente este punto es tomado por Emilio J. Corbiére para afirmar que "el Opus se mueve dentro de la mentalidad jurisdiccionalista, [postura de la Iglesia basada en el dominio y la imposición] matizada, tácticamente por una operatoria moderna en lo exterior. Debido a su impermeabilidad y reticencia –especialmente la de su fundador. Escrivá de Balaguer– al Concilio Vaticano II, ahondó  sus aspectos organizativos, ascéticos y apostólicos, claramente anacrónicos" (Corbiére 2002:18) . Por ende, es posible llegar a observar que los elementos que dan cuerpo al Opus son realmente la materialización de preceptos tradicionales en un contexto de modernidad; mientras ellos adhieren al control de sus miembros, se desarrolla una doctrina económica capitalista que lleva a los sujetos a desarrollarse de modo individual para maximizar su riquezas. 

Para el análisis del Opus Dei en tanto fenómeno religioso, se utilizarán dos conceptos que es necesario esbozar de forma preliminar. El primero de ellos tiene relación con el contexto histórico en el que Escribá de Balaguer organiza y configura la orden: los vertiginosos inicios del siglo XX. Utilizando la conceptualización propuesta por Marshall Berman, este período se enmarca en lo que el autor define como tercera fase de la modernidad, y en ella, confluyen distintas trayectorias de ideas filosóficas, ideologías y cosmovisiones respecto al mundo construidas a lo largo de, por lo menos, los últimos cuatro siglos anteriores (Berman, 1986).

Un elemento central de la tercera fase de la modernidad, es lo que aquí denominaremos ethos económico moderno, y refiere a una determinada concepción moral respecto a la economía, distinta a las concepciones tradicionales como el mercantilismo u otros modos económicos propios de las regiones del mundo que durante el siglo XX confirman un rol periférico. Esta concepción moral, que será abordada de forma más completa en páginas posteriores, se articula en las primeras fases de la modernidad, y se origina, siguiendo a Max Weber, en la ética económica calvinista (Weber, 2006). Con el transcurso de los siglos, y junto al desarrollo del capitalismo, el mundo moderno asume ciertos elementos centrales de esta ética hasta naturalizarlos y volverlos hegemónicos. La relación que el Opus Dei mantiene respecto a este ethos es estrecha, y a diferencia de otras ramas del catolicismo, abraza el código moral económico heredado del protestantismo y el puritanismo; es en función de esta relación, que podemos situar a la orden como un fenómeno religioso de matriz moderna (y no, por ejemplo, de carácter tradicionalista).

No obstante, la novedad del Opus Dei no es tanto la inclusión de concepciones éticas protestantes y puritanas en el mundo católico, como la reunión que estas directrices morales tienen con prácticas tradicionales. El uso del cilicio para mortificar la carne, la visión estática sobre la movilidad social, la aplicación sistemática de censura en la formación, así como el rol capital de la obediencia, responden a lo que aquí consideraremos como elementos diacrónicos dentro de la Obra. Resabios, guiños a un mundo pasado cuya relación con el cuerpo y el sujeto no estaba concebida desde los valores modernos desarrollados en las primeras fases de la modernidad (como la libertad).

Estos dos conceptos (ethos económico moderno y elementos diacrónicos), serán las variables utilizadas en la presente investigación. A través del estudio de su relación, se espera aprehender la complejidad que el Opus Dei aporta a los credos religiosos contemporáneos, revisando en el proceso los alcances sociales y económicos que la Obra supone en un contexto neoliberal.



## Problematización

### Pregunta investigativa:

¿Cómo se configura la cosmovisión económica y social del Opus Dei en la modernidad, respecto a la incorporación de elementos propios del orden tradicional?

-	**Objetivo general:**
  -	Determinar el modo en que se configura la cosmovisión del Opus Dei, considerando la relación entre elementos tradicionales y modernos.
-	**Objetivos específicos:**
  -	Determinar los elementos diacrónicos presentes en el Opus Dei.
  -	Determinar los componentes del ethos económico moderno presentes en el Opus Dei.
  -	Explicar cómo se entrelazan los elementos diacrónicos con los componentes del ethos económico moderno en el Opus Dei.

## Hipótesis investigativa

La cosmovisión del Opus Dei articula elementos tradicionales y modernos a través de un férreo dogmatismo religioso que facilita su coexistencia.

## Justificación y relevancia

El Opus Dei ha generado críticas tanto en el entorno religioso como en la sociedad civil. Por tales motivos, la importancia de esta investigación se centra en analizar el fenómeno del Opus Dei en el marco de la discusión existente sobre la modernidad, esto último es lo que distingue a esta investigación de las más clásicas, que utilizan como eje principal el análisis desde el poder o el vínculo que tiene el Opus con los sectores vinculados con lógicas empresariales, esto desde la perspectiva de que las enseñanzas del Opus Dei son funcionales a las prácticas capitalista, por lo tanto es relevante plantear que esta investigación, centrada en el Opus Dei, considera que su creación y permanencia se enmarcan en una relación dada entre los valores tradicionales y modernos.
La relevancia del estudio radica en que, al inmiscuirnos en las investigaciones existentes sobre el tema, hallamos que los tópicos que abordan el tema del Opus Dei consideran, en su mayoría, “el poder” como factor central en la creación de identidad y mantenimiento de la organización.  Frente a ello, esta investigación pretende dar una nueva óptica al estudio del fenómeno religioso Opus Dei, en donde se ahondará en las potenciales tensiones entre elementos tradicionales y modernos en la Obra.


## Estado del arte

### El Opus Dei desde las ciencias sociales.

Las investigaciones que se han desarrollado en ciencias sociales y humanidades en torno al Opus Dei se encuentran generalmente asociadas a la explicación de sus presupuestos centrales y la manera en que este se  ha configurado en el tiempo. El ejemplo emblemático de aquello es el libro publicado por Jesús Ynfante (1996), que se ubica como el estudio más amplio sobre la historia y estructura de la organización. En él el autor se concentra en explicar la vida de Josemaría Escrivá de Balaguer, la relación que mantiene con la Guerra Civil española, el auge que desarrolló en la posguerra, el ingreso de la orden religiosa al Vaticano, la configuración dentro de la orgánica y  la manera en que articulan los poderes.  En una vertiente similar se sitúa la investigación periodística de María Olivia Mönckeberg a la que denominó "El imperio del Opus Dei en Chile" (2004), con la que hizo explícito el modo en que se expresaba esa fracción de la iglesia católica en el país y el juego que su desarrollo con los organismos de mayor poder.

Como se puede observar, tanto en la investigación de Ynfante como en la de Mönckeberg, el tema central por el que deambulan los estudios es la composición de la orgánica y la relación que mantienen con las estructuras económicas y políticas de la época en la que se encuentran inmersas. El análisis de las relaciones de poder que se mantienen dentro de aquella es el eje vector que mueve a los investigadores a inmiscuirse en esta empresa  Por lo mismo, si sólo se contemplan investigaciones con estas características, se tendría clara la relación que mantienen con el franquismo en España y el ala más conservadora de la política chilena, pero ello sólo implicaría la aprehensión del fenómeno desde una arista particular que se presenta como central. Desde una postura más crítica, mas no por ello menos reductivista, se encuentra el estudio de Emilio J. Corbiére (2002), quien en "Opus Dei el totalitarismo católico" precisamente centra su atención en la configuración del Opus en asociación a los totalitarismos que se desarrollaron en España y América Latina durante el siglo XX. En sus páginas se descubre no sólo el modo en que aquella se relaciona con procesos dictatoriales sino que también, a la propia organización como autoritaria, marcada por ribetes fuertemente totalitarios.

Desde otra arista investigativa se encuentra la publicación realizada por  Marcia Gaymer Mogro-Moreno (2005), para optar al grado de licenciada en Sociología de la Universidad Alberto Hurtado. La autora en esta ocasión ve el Opus Dei como algo más que una organización eclesiástica que mantiene una relación constante con instituciones autoritarios; ella se concentra en la función ideológica que presta el Opus en relación a la legitimación del orden establecido. Para esta el elemento central en disputa es la comprensión de cómo un ethos económico capitalista se relaciona con la concepción del trabajo que se presenta la institución y el servicio que aquello puede prestar para la comprensión de la realidad de un modo determinado.

La presente investigación se concentrará precisamente en el ethos económico que menciona Gaymer, pero no exactamente en la relación a la legitimación del orden establecido. Como ya se ha podido comprender en las secciones anteriores, el tema central a tratar hace relación con la configuración del ethos económico en un contexto de modernidad y la manera en que aquello se puede comprender como un proceso en el que entran en juego elementos tradicionales y modernos, a través de la coexistencia armónica entre sus partes. La instancia que se articula en el informe llama a comprender el Opus Dei desde una concepción general, dejando de lado los estudios que se concentraban en el elemento autoritario y ampliando los que ya hacían visible la existencia de un ethos particular.

## Marco teórico

### Premodernidad, tradición, y el concepto de diacronía

Como ya fue mencionado, Marshall Berman propone una división operativa de la historia de la modernidad en tres fases, de acuerdo al grado de avance de la modernidad y su nivel de asimilación por parte de las sociedades. La primera fase, que abarca desde el siglo XVI al XVIII, se caracteriza por las primeras experiencias de vida moderna, y, en tanto novedad, las formas de comprenderla y relacionarse con ella resultan diversas y erráticas, sin que sea posible que constituya una identidad a partir de ella en el público. La segunda fase se inicia con lo que Berman llama la «gran ola revolucionaria de 1790», refiriéndose a la revolución francesa y sus repercusiones internacionales. Esta «ola» trae consigo nuevas formas de interpretación de la realidad y expande enormemente los horizontes de posibilidad de las culturas, pero, en medio de este ánimo revolucionario, el público aún recuerda “lo que es vivir, material y espiritualmente, en mundos que no son en absoluto modernos” (Berman 1988:2), dando lugar a una dicotomía interna de “vivir simultáneamente en dos mundos”, a la cual nosotros denominaremos «diacronismo». La tercera fase inicia con el advenimiento del siglo XX, a través de su proceso de modernización global, y en tanto expansión de tamaña magnitud, deviene fragmentada, y por ende la modernidad “pierde buena parte de su viveza, su resonancia y su profundidad, y pierde su capacidad de organizar y dar un significado a la vida de las personas” (Berman 1988:2).

En este sentido, y ubicándonos como sociedad en la tercera etapa, es posible afirmar, según Berman (1988), que la sociedad moderna “ha perdido el contacto con las raíces de su propia modernidad” (Berman 1988:3). Así, se articula nuestro problema investigativo, en el cual identificamos cómo el Opus Dei articula en su cosmovisión factores premodernos (tales como los mencionados en la segunda etapa de Berman, en la cual los colectivos aún recuerdan modos de vida anteriores), y a la vez notablemente modernos, como se explayará en la siguiente sección. Esta contradicción premoderno-moderno se desarrollará a través del concepto de «diacronía», opuesto al de «sincronía».

Los conceptos de diacronía y sincronía provienen del lingüista suizo Ferdinand de Saussure, durante finales del siglo XIX e inicios del siglo XX. Posteriormente, son aplicados por el filósofo Emmanuel Levinas durante las décadas de 1940 y 1970 en el campo de la fenomenología, ontología y psicología. Luego, durante los ’80, Ernst Bloch aplica los conceptos a la teoría marxista de la consecución de una sociedad de nuevo tipo.

En breves palabras, sincronía se define como sucesos que convergen en el tiempo, ocurriendo a ritmos idénticos. Contrapuesto a ella, la diacronía remite a un tiempo sin correlación al tiempo principal.

La sincronía, en Saussure (1945), es tiempo dominante, “es ley general, pero no es imperativa”, en tanto su imposición radica en la socialización (Saussure 1945:117) que sus diversas manifestaciones culturales producen (por ejemplo: la lingüística, la historia, etc.). En otras palabras, sincrónico es el tiempo que la mayor parte de la sociedad experimenta como único, puesto que es el que se les presenta de forma social, i.e. a través de su vida diaria e interacciones mundanas. Así, la sincronía es la “simple expresión de un orden existente, (que) consigna un estado de cosas” (Ibíd). Por el otro lado, la diacronía responde a cambios o sucesos que ocurren paralelamente a una historia de mayor orden (Saussure 1945:118); es decir, sucesos en cierta manera alternativos, o bien aislados, de la narrativa principal. Por esto, lo diacrónico radica aparentemente particular (Saussure 1945:117). Por lo tanto, y en contraposición al carácter dominante de la sincronía, la diacronía, si quisiese posicionarse como tiempo principal, debe necesariamente adoptar un carácter imperativo –en contraposición a la generalidad espontánea de la sincronía–, en vista de que su particularidad requiere alzarse sobre la “ley general” de una forma que agrupe a sus hechos de apariencia particular (Ibíd). La agrupación de los hechos requiere, entonces, un carácter que les de una forma que supere la mera accidentalidad, confiriendo una identidad a los factores comunes que se atribuyen a su surgimiento. Si bien Saussure desarrolló el concepto de diacronía para su uso en la lingüística, su aplicabilidad es extrapolable a numerosos sucesos sociales, como lo es, para nuestro caso, el Opus Dei.

Como aplicación de los conceptos de diacronía y sincronía al estudio de la ideología en el capitalismo, Bloch (1982) caracteriza la diacronía como un tiempo que no ha sido asimilado (Bloch 1982:114). Así, la agudeza de la contradicción diacrónica religiosa se encuentra, en cierto sentido, congelada en el tiempo, en tanto su magnitud de praxis (su capacidad de participar en el mundo) se mantiene invariable (en tanto historia alternativa y anterior, como se verá más adelante), y su capacidad de devenir en crisis se ve anulada, puesto que, ya que resulta tiempo alternativo, su asimilación en la sociedad en su conjunto es nula, puesto que se ve imposibilitada de participar en los procesos y evoluciones históricas de la sincronía.

> “La contradicción diacrónica en el plano subjetivo es furor contenido, y como desigualdad objetiva de desarrollo es pasado no resuelto.” (Bloch 1982:114)

La antítesis que se genera de la contradicción diacrónica es la de una “clase sin historia”, en tanto sus ideas y prácticas identitarias se encuentran aisladas y por ende contrapuestas a la historia de la sociedad en que se sitúa. En base a esto, la diacronía se manifiesta como una fractura de los intereses sociales más amplios (los sincrónicos), puesto que reivindica unos intereses caducos y alternativos. (Bloch 1982:115). Así, la diacronía convive con la historia de otras clases como una ahistoricidad, persistiendo en su auto-afirmación, incubándose y eventualmente manifestándose de forma extrínseca, sin que sus demandas o conflictos apunten hacia problemas estructurales de la sociedad, sino a sus propios problemas comunitarios (Bloch 1982:115).

Según Bloch, la contradicción sincrónica tiene –como medio para cumplir su meta (que sería el cambio cualitativo de la sociedad a través de la superación de la contradicción trabajo/capital)– que aumentar en alcance y eclipsar a la contradicción diacrónica, absorbiendola hacia sus intereses (las fuerzas progresivas) (Bloch 1982:115). Esto se complementa con los argumentos de Saussure: cuando la diacronía requiere superar a la sincronía si es que desea posicionarse como tiempo general, la sincronía, si desea realizar su crisis y contradicción, tiene que absorber y asimilar a la diacronía. En efecto, observamos cómo se articula la contradicción.

Continuando la idea de contradicción diacronía-sincronía de Bloch-Saussure, incorporamos el sentido levinasiano de los conceptos. Maturano (2002) afirma que, en Levinas, “la diacronía se contrapone a la sincronía”, validando la contradicción que planteamos. El tiempo diacrónico entra en relación con el sincrónico, pero no es sintetizado por él: es decir, es capaz de experimentar una cierta línea de tiempo paralela (Maturano 2002:67). En esta línea de tiempo, colisionan dos «épocas separadas», que se manifiestan en identidades sociales diferentes. Esto le constituye al tiempo diacrónico una naturaleza de “ser-uno-con-el-otro”, es decir, una cierta dependencia del «suceso otro» visto como futuro (la sincronía).

Visto desde el punto de vista diacrónico, esta relación entre el otro (sincrónico) y el yo (diacrónico) se manifiesta como una relación decir-respuesta (Maturano 2002:68), donde la respuesta siempre proviene de un «otro trascendente» (la sincronía), lo que a su vez devela la discontinuidad temporal. Este contexto de tiempo discontinuo y su relación interna yo-otro cimienta a la sincronía como futuro, del cual se espera la respuesta como «futuro inhibido» (Bloch 1982:114), imposible de anticipar, y por ende, creador de la dependencia diacronía-sincronía.

En resumen, y de acuerdo a esta discusión conceptual, es posible identificar una contraposición de los conceptos diacronía y sincronía, en la cual la sincronía toma el lugar preponderante, y que actualmente corresponde al lugar de la historia occidental, o bien del ethos económico moderno (según se argumenta más adelante), mientras que la diacronía responde a los resabios de historias pasadas que siguen siendo experimentadas por diversos grupos sociales como una historia alternativa, anterior a lo sincrónico, pero en un diálogo negativo con ello. La aplicación al problema investigativo radica en la forma en que el Opus Dei, a diferencia de otros credos o grupos religiosos, aprehende las historias sincrónicas y diacrónicas de una forma internamente coherente y aparentemente exitosa, lo cual sería conceptualmente complejo (o derechamente imposible) de acuerdo al marco teórico recientemente expuesto.

Pero, al concluir que la diacronía corresponde a la lucha por el reconocimiento de las “historias pasadas”, vale replantear la calificación de este tiempo cultura como “premoderno” realizada a través de Berman, cuya aplicación frente al Opus Dei en la presente investigación apela a un momento moderno que recuerda las formas de vida pasadas, donde Berman afirmaría –como ya fue expuesto– que existe una pérdida de raíces de la modernidad respecto de su pasado (Berman 1988:3).

En este sentido, metodológicamente pareciera ser más preciso tratar el problema investigativo a través del concepto de «tradición» de Balandier (2005), en tanto éste hace referencia a la resistencia temporal de factores sociales de antaño dentro de la modernidad, mientras que el concepto de premoderno apelaba a factores del pasado cuya aparición en el presente resultaría negativizada de por sí. Considerando el caso en que los factores sociales pretéritos del Opus Dei dentro de nuestra sociedad sí encuentran cabida dentro de su lógica y coherencia grupal, llamarlos premodernos significaría hacer hincapié en la disonancia del tiempo pasado con el tiempo de estudio, e ignorar la integración que esta agrupación religiosa realiza respecto de los conceptos cargados de temporalidad.

En vista de lo anterior, procedemos a tratar el concepto de «tradición», el cual, según Balandier, representa la base cultural y discursiva capaz de generar una continuidad entre cambios sociales y temporales (Hervieu-Léger 2005:144). Al respecto, es la tradición la que construye los códigos de sentido, valores, y normas sociales que permiten la cohesión necesaria para la conformación y mantención de grupos a través del tiempo (Baladre 1988, Hervieu-Léger 2005:140), como lo puede ser el Opus Dei. Sería la tradición la que juega el rol de recuperación de las raíces de la modernidad, en tanto continuidad –el problema que vio Berman y que fue explicitado anteriormente; y, a su vez, se vuelve posible identificar a través de la argumentación de Hervieu-Léger (2995:140) que la base tradicionalista de las religiones, en vez de ser un factor anti-modernidad (como se trata generalmente al hablar de religiones tradicionalistas), en realidad encuentra su fundamento al interior de ella, como se explicará a continuación.

Los aspectos tradicionales, para los grupos sociales, son herencias del pasado que se ven reincorporados de forma hermenéutica en la modernidad, dando un testimonio actualizado de forma constante de los orígenes del momento presente (Hervieu-Léger 2005:145, 146), en el sentido de que se hacen propios aspectos de la forma social anterior, pero adecuados de tal manera que su significancia genere un marco de sentido para la forma social del presente. En otras palabras, los grupos sociales generan una re-lectura de los factores pretéritos, adecuándolos a las realidades modernas de forma contingente, para así re-apropiarlos utilitariamente, con la finalidad de construir una base de legitimación basada en la argumentación tradicionalista. Es necesario comprender que esta reinterpretación contemporánea es vital para generar la tradición como forma de cohesión social, puesto que, de lo contrario, las categorías de sentido simplemente serían incapaces de calzar en tanto su propio nacimiento fue reflejo de ciertas condiciones productivas y culturales que simplemente se encuentran ausentes en el tiempo presente. Es por esto que “toda tradición se elabora a través de la reelaboración permanente de los datos que un grupo o una sociedad recibe de su pasado.” (Hervieu-Léger 2005:146).

Este proceso hermenéutico es capaz de construir una relación del presente sincrónico con el pasado diacrónico, siempre en función de la hegemonía sincrónica (es decir, de la interpretación situada en el presente), configurando de esta manera una nueva relación con el presente al incorporar en ella el código de sentido tradicional, cuyo valor de continuidad se basa en el hecho de que vuelve posible el posicionamiento del origen de su mundo en un espacio fuera del tiempo mismo, materializando así la diacronía como una realidad social utilitaria capaz de ordenar al mundo de forma extrasocial (Hervieu-Léger 2005:141). Este factor es de gran importancia para tratar al Opus Dei en un marco temporal: la ordenación de los grupos religiosos recae en un posicionamiento fuera del mundo, y, mediante este movimiento argumentativo, se sitúa al cimiento de la religión en una posición tal que queda fuera del alcance de “la acción transformadora de los hombres” (Ibíd), garantizando, de esta manera, su solidez estructurante.

De esta manera, es posible identificar la estrategia de la diacronía para superar a la sincronía no es oponérsele, sino crear una solidez organizativa en sus manifestaciones sociales que deviene inamovible y coherente consigo misma, dotándose de sentido y cohesión a un nivel que la sincronía difícilmente podría alterar.

En este sentido, puede ocurrir la coincidencia entre ethos económico moderno y tradición del Opus Dei, ya que, al generarse la base estructural que permite la existencia del grupo religioso fuera del tiempo sincrónico –por medio de una dotación de sentido sólida que recae en al tradición extra-social, su existencia organizativa se vuelve, de cierta manera, independiente y modular del resto de los valores sociales (al poseer una nueva y diferente fuente de sentido), y así es capaz de situarse en diferentes contextos temporales y culturales sin desestabilizarse, sino que rearticulándose por medio de una operación hermenéutica de interpretación de su tradición basal.

### El ethos económico moderno

Para construir el concepto ethos económico moderno, se utilizó a dos autores fundamentales: Max Weber y Adam Smith. El primero, en su célebre escrito La ética protestante y el espíritu del capitalismo (1991), establece la conformación de un ethos capitalista a partir de la visión del trabajo y la profesión en las corrientes religiosas protestantes. El segundo, puritano, inmerso precisamente en las nociones protestantes que Weber analiza, erige los pilares de la teoría económica liberal que, hasta el día de hoy, priman en el capitalismo moderno.

Ciertamente, utilizar a Adam Smith como fuente de análisis no es una decisión casual. Siguiendo el esquema de Marshall Berman (nuestro telón de fondo), un elemento clave de la modernización es el desarrollo del capitalismo moderno. Su expansión sin precedentes a lo largo del siglo XX gatilla una serie de procesos políticos, económicos y sociales (expansión demográfica, migración campo-ciudad, la llamada cuestión social, las transformaciones en el Estado moderno, etc.) que incrementan la percepción de una vorágine, imagen con la que Berman grafica a la modernidad. Si bien la modernidad se divide en tres fases, la inclusión en el Opus Dei de visiones protestantes respecto al trabajo y la economía, nos lleva a mirar principalmente hacia el capitalismo, y sólo de forma tangencial o secundaria a otros procesos modernos. En este punto, la inclusión del trabajo de Max Weber es imprescindible.

Uno de los principales recursos de Weber en lo que a fuentes refiere, son las máximas escritas por Benjamin Franklin en Advertencias necesarias a los que quieren ser ricos. Escrito en 1736, representan para el autor un ejemplo clave de lo que él llama el espíritu del capitalismo. Una cierta visión, orientación y disposición hacia el trabajo y el dinero que subvierte la tradicional visión católica, que por lo general, ve con más malos ojos la afición al trabajo con el fin de hacer dinero (precisamente, la imagen católica del usurero es una forma de etiquetar y caricaturizar dicha afición de forma despectiva).

En la primera mitad del siglo XVIII (lo que equivale a decir “en la primera fase de la modernidad”), Benjamin Franklin escribía:

> “Considera que el dinero es fecundo y provechoso. El dinero puede engendrar dinero, los sucesores pueden engendrar aún más y así unos a otros. Si cinco chelines son bien colocados, se convertirán en seis, éstos, a su vez, en siete que, asimismo, podrán devenir en tres peniques, y llegar en sumas sucesivas hasta constituir un todo de cien libras esterlinas. A cuanto más dinero invertido, tanto más es el producto. Así, pues, el beneficio se multiplica con rapidez y en forma constante. Aquel que mata una cerda, reduce a la nada toda su descendencia hasta el número mil.

Aquel que derrocha una moneda de cinco chelines, destruye todo cuanto habría podido originarse con ella: montículos compactos de libras esterlinas.” (Weber 1991:20)

En la cita, puede apreciarse con claridad que el derroche es mal visto no por ser considerado un exceso, sino porque trunca un potencial desarrollo del capital actual y futuro. Esta mentalidad particular, es inexistente antes de la primera fase de la modernidad. Para explicar su origen, Weber acude a las concepciones protestantes sobre el trabajo: “En cualquier caso, lo nuevo, de manera absoluta, era que el contenido más honroso del propio comportamiento moral consistía, precisamente, en la conciencia del deber en el desempeño de la labor profesional en el mundo. Esa era la ineludible secuela del sacro sentido, por así decir, del trabajo y de lo que derivó en el concepto ético-religioso de profesión: concepto que traduce el dogma extendido a todos los credos protestantes, opuesto a la interpretación que la ética del catolicismo divulgaba de las normas evangélicas.” (Weber 1991:41).

A su vez, la posición en el mundo (de la cual se deslindan consecuentemente ciertos deberes, trabajos o profesiones) no posee una lógica azarosa. En este punto, la herencia de Calvino (1509-1564) es fundamental. Para el teólogo protestante, “Dios ha creado lo que quiere hacer de cada uno de los hombres. Porque él no los crea a todos con la misma condición, sino que ordena a unos para la vida eterna, y a otros para la condenación perpetua. Por tanto, según el fin para el cual el hombre es creado, decimos que está predestinado a vida o muerte.” (Calvino 1967:29) Esta forma de comprender la posición social según decisión divina no dista demasiado de las nociones que organizan la sociedad de la Europa medieval, en donde tres estamentos (oratores, bellatores y laboratores) poseen una función previamente determinada, sin embargo, está lejos de la idea actual de movilidad social.

En 1763, el puritano anglosajón Adam Smith escribe La riqueza de las naciones, obra que reúne los elementos posteriormente identificados por Weber en un texto que será fundamental en las restantes fases de la modernidad. Existen menos de treinta años de diferencia entre los textos de Franklin y Smith, ambos están inmersos en la búsqueda de un lenguaje moderno que caracteriza al siglo XVIII según Berman, y colaboran en el asentamiento de las bases del ethos económico moderno. Al papel que el protestantismo le asigna a cumplir el deber (ética del deber, ética de la profesión), Smith sumará nuevos elementos en torno al trabajo: “esta motivación del trabajo, que tantas ventajas reporta, no es en su origen efecto de la sabiduría humana... es la consecuencia gradual, necesaria aunque lenta, de una cierta propensión que no aspira a una utilidad tan grande: la propensión a permutar, cambiar y negociar una cosa por otra” (Smith 1958:15). Siguiendo a Smith, ya no sólo existe una motivación del trabajo, además, destaca una disposición hacia el comercio. Si esta propensión no proviene de la sabiduría humana, sólo puede venir de Dios. Es él, pues, quien define la estructura social (quién ha nacido rico y quién ha nacido pobre, quién está destinado al cielo y quién al infierno), y al mismo tiempo instala en los hombres la vocación comercial que deriva en una sociedad de comercio.

Por último, Smith señala que “una sociedad que reverencia la conquista de riquezas como la suprema felicidad, ha de hallarse naturalmente dispuesta a considerar al pobre como condenado de antemano al fuego eterno, aunque sólo sea para hacerle de este mundo un infierno” (Smith 1958:20). Así, la predestinación y la orientación comercial se reúnen en una elaboración ética sobre la sociedad. Si bien esta elaboración no es del todo homologable con la ética económica actual (en donde la economía, en apariencia, está alejada de la religión), constituye la matriz desde la que se elabora nuestro ethos económico moderno. Para entender este proceso gestionado en siglos, es necesario recurrir a la conceptualización sobre el tiempo realizada por Fernand Braudel. Para el historiador francés, existe un tiempo histórico mayor a la coyuntura, mayor al acontecimiento. Se trata de la larga duración histórica, en la que se desarrollan fenómenos difíciles de desgastar, atravesando toda clase de coyunturas. Ejemplos de ella son “ciertos marcos geográficos, ciertas realidades biológicas, ciertos límites de la productividad, y hasta determinadas coacciones espirituales: también los encuadramientos mentales representan prisiones de larga duración.” (Braudel 2006:9)

La modernidad, tal y como la entiende Marshall Berman, reside en la larga duración histórica. Asimismo, el ethos económico moderno es un proceso de largo aliento que ha sufrido transformaciones, pero que mantiene una estructura que no se desgasta con el transcurso de los años. Es, en este sentido, un encuadramiento mental, mediante el cual se ha forjado de forma permanente a lo largo de la modernidad una orientación hacia la acumulación del dinero, y una ética del trabajo en la que la responsabilidad y el cumplimiento del deber son trascendentales. Nuestra investigación, buscará identificar los componentes del ethos económico moderno presentes en el Opus Dei, los que son comunes a la gran mayoría de la sociedad, y aquellos que tienen un vínculo más cercano a la posición religiosa puritana.

Diacronismos y ethos económico moderno: una extraña comunión.

A partir de la discusión teórica anteriormente expuesta, se llega a un diagnóstico sobre la cosmovisión económica y social del Opus Dei, en el que destaca la presencia de elementos diacrónicos propios del orden tradicional, en el contexto de la tercera etapa de la modernidad.

Estos elementos diacrónicos, entendidos por Bloch como un pasado no resuelto, revisten para el autor un peligro potencial, una puerta entreabierta a antiguos problemas hechos presentes, al ingreso de valores que pueden poner en jaque los procesos históricos y sociales contemporáneos. El ejemplo que utiliza Bloch, refiere al surgimiento del nazismo, pues para él, su auge no puede explicarse por simple espontaneísmo, sino por aquellos elementos diacrónicos que nunca fueron solucionados: el antisemitismo, la idea medieval de un territorio que devendrá en la noción de espacio vital, y el discurso de supremacía racial germánica (Bloch 1982).

En esta línea, es posible identificar elementos diacrónicos en las prácticas y el discurso del Opus Dei. Éstos corresponden a patrones morales tradicionales, es decir, anteriores al advenimiento de la modernidad: censura, mortificación de la carne, obediencia ciega y visión estática-estamental de la sociedad. Todos estos elementos, desencajan con los valores que se masifican en la tercera etapa de la modernidad, entre ellos, la libertad, el pluralismo y el ascenso social. 

En el documental de Marcela Said “El Opus Dei en Chile, una cruzada silenciosa”, se entabla el siguiente diálogo con Luis Alejandro Silva, numerario, estudiante de la Pontificia Universidad Católica de Chile y proyecto político de la obra:

— **Periodista:** ¿Tú puedes leer lo que tú quieras?, ¿ir al cine a ver lo que tu quieras?
— **Luis:** No.
— **Periodista:** ¿Me puedes contar más?
— **Luis:** Es que eso va a sonar demasiado mal, prefiero no...
— **Periodista:** Pero es cierto, o no es cierto?
— **Luis:** Sipo.
— **Periodista:** Es el tema que me preocupa, por eso te lo pregunto.
— **Luis:** Bueno es que yo te respondería que leo lo que yo quiero, y no voy al cine. Eso te respondería.” 

A pesar de que el joven numerario reconoce que la imposibilidad de leer y ver en el cine las películas que quiera es problemática, para el sacerdote José Miguel Ibáñez Langlois, crítico literario y emblema dentro de la obra del Opus Dei en Chile, “en el caso del Opus Dei, no hay nada que pueda llamarse censura (…) lo que hay son medidas mínimas de prudencia en la formación intelectual de los fieles” (Ibáñez 2011). Por medio de este eufemismo, Ibáñez resignifica la censura aplicada al adoctrinamiento religioso; esta estrategia discursiva es acompañada de su propia experiencia, en la que, por ejemplo, la lectura de Nietzsche le significó “sudar tinta” (Ibáñez 2011), algo que él desea evitar en los nuevos fieles. 

Otro elemento diacrónico del Opus Dei, y fuente permanente de debate, es su visión estática-estamental de la sociedad. Para el fundador, “tu perfección está en vivir perfectamente en aquel lugar, oficio y grado en que Dios, por medio de la autoridad, te coloque” (De Balaguer 1939:130), un pensamiento novedoso en el catolicismo, pero de vasta tradición en el protestantismo (como vimos con anterioridad, la noción de predestinación en Calvino también apunta a prosperar en el lugar en donde se ha nacido), que poco tiene que ver con la disposición hacia el ascenso social que el modelo económico liberal y neoliberal proponen (es decir, abiertamente distante del ethos económico moderno). En este diacronismo, la sociedad aparece como un cuerpo compuesto de partes destinadas a actuar según la función que les corresponde, por lo que la movilidad social representa un desorden innecesario e incluso peligroso. 

Bajo esta línea de pensamiento, Ronald brown, ex presidente de los exportadores chilenos, actual presidente de ASOEX (Asociación de exportadores de frutas) e integrante de la asociación de amigos de Nocedal, una fundación educativa para sectores vulnerables al alero de la Obra, afirma que para los empresarios resulta importante aportar dinero a esta fundación porque “en primer lugar, tener trabajadores que estén mejor dispuestos, con mejor disposición de ánimo, con una comprensión mayor de lo que es la sociedad; y en segundo término, que ellos contribuyan a la armonía social…” (Brown 2006)

Así, los empresarios, en la posición social que les corresponde por autoridad divina, invierten su dinero en un proyecto educativo que no sólo les proveerá de buena mano de obra, sino de un conjunto social formado en su particular visión de la armonía social, una “sólida formación humana, inspirada en los valores cristianos” (Nocedal 2009:4). 

Estos elementos, sumados a la mortificación de la carne como una práctica reconocida, son aquí comprendidos como diacronismos. Éstos resultan problemáticos en la medida que coexisten con actitudes y disposiciones cotidianas propias del aquí llamado ethos económico moderno.

Tal y como registra la revista de negocios América Economía, el Opus Dei posee diez prestigiosas escuelas de negocios en América Latina: IESE Business School (con sedes en Madrid, Barcelona y Nueva York), IPADE de México, IAE de Argentina, PAD de Perú, ESE de Chile, INALDE de Colombia, ISE de Brasil, IDE de Ecuador, IEEM de Uruguay y UNIS de Guatemala.. Este vínculo con el empresariado no es casual. Como se explica en el citado documental de Marcela Said, la posibilidad de enriquecerse a través de los negocios no es criticado ni visto con sospecha en este credo. Dado lo anterior, se presenta como una interesante alternativa religiosa para aquellos miembros de la elite económica que no desean juicios morales en torno a sus actividades comerciales, y al mismo tiempo tienen inquietudes espirituales de raigambre católica. 

Esta característica del Opus Dei también proviene de la inclusión de valores puritanos. Siguiendo los supuestos de Adam Smith, el hombre es egoísta por naturaleza, su propensión a producir bienes no se debe a una tendencia empática hacia un otro, sino a la búsqueda de su propio beneficio. De este agasajo personal, la sociedad en su conjunto se ve beneficiada, ya que gracias a él existen los bienes y servicios que permiten su reproducción. Esta premisa moral, justifica la actitud comercial y la importancia de los empresarios  para el bien común. El enriquecimiento que esta actividad puede generar, vista como problemática en ciertos pasajes bíblicos (“Es más fácil para un camello pasar por el ojo de una aguja, que para un rico entrar en el reino de Dios.” Marcos 19:24), será sólo la consecuencia de un trabajo bien realizado que, además, redunda en un bienestar colectivo.

Esta lectura, que en el puritanismo anglosajón proviene de las tesis de Calvino, en el Opus Dei no son argumentadas de forma extensa. Salvo algunas breves palabras del fundador, su existencia se debe más bien a una acción sistemática: la legitimidad no está en la lógica argumental de esta disposición empresarial, sino en su práctica cotidiana. Son los fieles que efectivamente viven y hacen carne este formato religioso quienes validan sus alcances morales. 

Ronald Brown lo explica con ligereza en el documental de Marcela Said: “Yo creo que cualquier católico tiene que buscar la santidad. Lo que aporta el Opus, es una santidad muy aterrizada, es la santidad en la vida ordinaria, en el contacto con la gente, en el trabajo bien hecho, en el respeto por los demás, en hacer las cosas bien profesionalmente. Y no en buscar una espiritualidad beata, no se trata de eso.” (Brown 2006)

Dicho de otro modo, un empresario que gana millones ya no teme por su entrada en el cielo, sino que puede sentirse satisfecho porque esa acción, es en realidad un motor de su propia salvación. Esta inversión de los valores católicos, se condice con lo que conceptualizamos como ethos económico moderno. Sólo resta entonces, comprender de qué forma pueden ser conciliados y amigados elementos tan disonantes como la estática movilidad social y el impulso empresarial; para ello, se analizarán dos obras fundamentales de Escrivá de Balaguer, Camino (1934) y Amigos de Dios (póstuma, 1977), buscando en ellos las claves que permiten este tramado. Pero antes, es necesario hacer una breve repaso por uno de los conceptos clave para nuestras lecturas: el dogma.

Antoni Defez (2000), filósofo y ensayista italiano, define el dogma como “...aquellas verdades directamente reveladas por dios, y así reconocidas por la Iglesia, que constituyen objeto obligado de fe para los creyentes.” Sin embargo, esta definición no aborda de manera tal nuestra tesis, ya que en esta investigación se suscita la idea de que existen, detrás del objeto obligado de fe para los creyentes, conjuntos de reglas que mantienen el orden y se manifiestan como dogma. En esa lógica quedarían fuera disciplinas dogmáticas que dependen del uso de la memoria, tanto histórica, tradicional o de forma práctica -tales como la geometría y/o disciplinas filosóficas-. Es por ello que  se recurre a Immanuel Kant (2010) quien hace rechazo a los dogmas en favor a la crítica de la razón, esto nos dice que la razón sería la que determina cuales son los conocimientos puros a priori que están detrás de las lógicas del Opus Dei y no, por lo tanto, un dogma definido al estilo de Defez (2000). Al encontrar estas inconsistencias es que se debe reelaborar una definición del dogma, y para ello debe hacer entrada el término dogmático, por lo tanto se definirá el dogma como verdades aceptadas sin crítica o examen alguno, y dogmático como aquel o aquellos que aceptan y/o pretender influenciar a otros hacia su aceptación, esta definición que se ha elaborado teniendo en cuenta el curso de la investigación abarca hechos, situaciones o acciones que también se pueden encontrar fuera de los ámbitos religiosos. A su vez se debe tener en cuenta que ideas, tales como el escepticismo, parecieran ser una negación al dogma, sin embargo este puede poseer principios dogmáticos, por ello profundizar en el escepticismo haría que, probablemente, la investigación se contradijera. 

En las acciones que se dan en los seguidores del Opus Dei vemos que el dogma también se vuelve una figura simbólica que “...constantemente son presentados como parte integrantes de la fe” (Meunier 2002) estas figuras simbólicas están revestidas de autoridad y tienen un fin concreto, es decir que el dogma se presenta como una “necesidad que tiene un grupo de personas cada vez más numeroso y diverso, de otorgarse señas de identidad y referencias comunes cuya aceptación permita verificar la pertenencia al grupo” (Meunier 2002), esto ocurre cuando el lenguaje de la teología se vuelve complejo, es decir que el dogma entre a representar una especie de cristalización pedagógica de la fe, aún cuando la fuente primaria de la religión católica sea la sagrada escritura, la argumentación que se quiere dar es que el dogma es más racional que la lectura que se le puede dar a la biblia, por ejemplo antes del fenómeno dogmático que se instala en las religiones, las creencias cristianas seguían utilizando medios para imponer y hacer creer su visión, ahí encontramos la persecución contra los categorizados como herejes, es decir que la existencia de mecanismo de indole dogmático no son nuevos, más bien sólo se han transformado según los acontecimientos que ocurran dentro y fuera de la religión misma. Por lo tanto, y a manera de concluir este apartado, es que se propone que el dogma, socialmente, tiene una visión peyorativa, a su vez es esencialmente negativa, ya que dice todo lo que no hay que creer ni hacer, sin embargo el dogma no pretende, bajo ninguna circunstancia, encerrar la fe en fórmulas ni ligar nunca el creyente a ellas. Esto lo podemos comprobar al observar, en este estudio, más de cerca el campo de fórmulas dogmáticas que utiliza el Opus Dei, más bien este sirve como una forma de cohesión social dentro de los seguidores de la rama católica y, como ya se planteo, los dogmas no presentan un hecho novedoso, ni tampoco es la única forma de cohesión, ya que vemos que existen símbolos, sacramentos y liturgias que tienen el mismo rol y efecto que el dogma. 

### El dogma como respuesta

Una vez comprendido los componentes teóricos asociados al modo en que el Opus Dei articula lo que acá reconocimos como el ethos económico moderno y el orden tradicional, es necesario aclarar la forma en que aquello se expresa en la praxis. En la vida cotidiana los miembros de esta congregación religiosa concentran su aprehensión de la realidad  a través de una fuerte influencia dogmática, que le otorga sentido a los componentes principales que guían su vida; la adhesión a una práctica económica neoliberal y una vida íntima, regulada por una divinidad omnipotente.

Para la explicitación de la manera en que se articula el dogmatismo dentro del Opus, se presentará a continuación el análisis de dos de los principales textos de Josemaría Escrivá de Balaguer; "Amigos de Dios" (1977) y "El camino" (1939). El primer escrito corresponde a un libro póstuma del fundador del La Obra, recogiéndose en él dieciocho homilías que desarrolló entre 1941 y 1968, abordando lo que aquél consideraba como diversos aspectos de la vida de cristo. Por su parte, el segundo se reconoce  como una meditación personal del fundador, en el que se abordan los diversos aspectos de la vida cristiana. Con ambos textos será posible vislumbrar claramente la manera en que el dogmatismo ingresa a la vida de sus adherentes y el modo en que articulan su vida en concomitancia con aquello, tanto en su fuero interno (prácticas personales) como externo (ethos económico)

#### Amigos de Dios

En el libro Amigos de Dios (1977) se precisan una serie de indicaciones relacionadas con el ejemplo de vida que representa Cristo para Josemaría Escrivá de Balaguer, destacando una sucesión de aseveraciones que le permitirían otorgarle sentido al actuar de los miembros de la congregación, especialmente asociado a elementos que posibilitan la relación, entre una concepción mercantilista que busca la maximización de los recursos y una vida espiritual, que espera asemejarse a lo que interpretan como ejemplo de vida del creador. En el juego de relaciones que le otorgan coherencia al modo que interpretan y actúan en el mundo, el fundador afirma la necesidad de cumplir con las tareas materiales (mercantilistas), pero siempre conscientes y en relación a los preceptos del cristianismo. Es así como en como en la premisa N°5 relaciona ambos elementos aparentemente antagónicos del siguiente modo:

> "Ya podéis llegar a la cumbre de vuestra tarea profesional, ya podéis alcanzar los triunfos más resonantes, como fruto de esa libérrima iniciativa que ejercéis en las actividades temporales; pero si me abandonáis ese sentido sobrenatural que ha de presidir todo nuestro quehacer humano, habréis errado lamentablemente el camino"  (Escrivá de Balaguer 1977:5)

El camino para Escrivá corresponde a la ejecución de las acciones necesarias en la vida para que sea posible ser envestido como santo, todas las personas tendrían la opción de serlo, dependiendo sólo de la forma en que configuran su manera de vivir. Ahí el elemento económico se manifiesta como un triunfo de la actividad material, que en nada imposibilita la opción de ser digno de santificación en tiempos futuros. Lo importante para ser canonizable se encontraría en la "vida íntima", lugar en el que se ubica la exigencia a ser dignos del amor al maestro. Esto en términos del fundador se reconocería como "una exigencia de la llamada que el Maestro ha puesto en el alma de todos" (Escrivá de Balaguer 1977:3)

Bajo la lógica expuesta todas las personas tendrían la capacidad y opción de ser santos, dependiendo sólo de la ejecución de las acciones consideradas como deseas por la divinidad. Ello implica también, la negación de todos los comportamientos que contradigan el supuesto designio divino, por ende, el actuar en el mundo público debería ser regido por los mismos preceptos dogmáticos que estructuran la vida privada. Por lo mismo, el religioso afirmaba en una de sus homilías que "podéis lograr los éxitos más espectaculares en el terreno social, en la actuación pública, en el quehacer profesional, pero si os descuidáis interiormente y os apartáis del Señor, al final habréis fracasado rotundamente.” (Escrivá de Balaguer 1977:5) . Por ende, el ethos económico moderno no sería en ningún caso contradictorio, mientras no contradiga los preceptos que se creen necesarios para ascender en el camino a la santidad.

Ahora, en la vida íntima los adherentes no tendrían la capacidad de cuestionarse las leyes que rigen su vida, sino que estarían obligados a seguir los principios dogmáticos establecidos por el Opus, esperando alcanzar con ello la posición espiritual anhelada. El propio Josemaría Escrivá de Balaguer llama a que no rebatan los designios que Dios le ha mostrado como imprescindibles, dado que aquello implicaría que realmente no lo aman, pese a que crean en él fervientemente. Explícitamente esto se expresa cuando en una de sus homilías menciona:

> "Si alguno dice: sí, yo amo a Dios, al paso que aborrece a su hermano, es un mentiroso (1 Ioh IV, 20.). Pero también se engaña el que regatea al Señor el amor y la reverencia –la adoración– que le son debidos como Creador y Padre Nuestro; y el que se niega a obedecer a sus mandamientos, con la falsa excusa de que alguno resulta incompatible con el servicio a los hombres, pues claramente advierte San Juan que en esto conocemos que amamos a los hijos de Dios, si amamos a Dios y guardamos sus mandamientos. Porque el amor de Dios consiste en que observemos sus mandatos; y sus mandatos no son pesados (1 Ioh V, 2–3.)" (Escrivá de Balaguer 1977:80)

Pues bien, con lo expresado hasta el minuto se puede observar que la asociación entre un ethos económico moderno y el orden tradicional se encuentra en una fuerte influencia dogmática, que hace que los adherentes al Opus no cuestionen en caso alguno los preceptos religiosos, pese a que les puede parecer más o menos coherente. La creencia ciega en los designios de la divinidad, lleva a que estos actúen en el mundo público bajo los preceptos económicos modernos de la maximización individual de la riqueza, mientras en ello nada contradiga lo establecido por la religión

#### El Camino

Publicado por primera vez en 1934, sólo dos años antes del inicio de la guerra civil española, Consideraciones espirituales es un extenso ideario que incluye 999 pensamientos; 999 consejos de Monseñor Escrivá de Balaguer a sus lectores. En 46 segmentos, aborda distintas áreas importantes para el devenir cotidiano de un seguidor de Cristo, de un apóstol en la tierra. Virtudes, actitudes fundamentales, posibles vacilaciones y sus respuestas, ordenanzas y mandatos. Este texto, está estructurado como un mensaje revelador, como la prolongación de una epifanía personal, a través de la cuál el lector puede apropiarse de su contenido, haciendo suyo este particular formato católico. Las últimas frases del primer segmento resonarán a lo largo de libro: “Y te metas por caminos de oración, y de amor, y acabes por ser alma de criterio” (De Balaguer 1939:2).

El objetivo fundamental de las Consideraciones espirituales, sería pues construir un criterio determinado. Para ello, el libro sigue una trayectoria que se inicia con un llamamiento a transformar la vida mundana por una apostólica, mediante un determinado carácter, y culmina con la importancia de la perseverancia. Es posible tomar este libro como una hoja de ruta, un mapa espiritual que puede ser leído de comienzo a fin al ser iniciado en los fundamentos de la obra, o abierto en cualquier punto para encontrar un mensaje azaroso. Su formato, hace de este libro una suerte de compilado de proverbios. Frases cortas y directas que sirven de directriz: un camino.

En 1939, para su segunda edición, el libro cristaliza este rol moralizante y pasa a llamarse El Camino. Un nombre más preciso, acorde con el objetivo de su mensaje. Dentro de las 999 confidencias (así las llamará el autor), es posible encontrar la importancia del dogmatismo para explicar los mandamientos del Opus Dei; una de las principales claves que se repiten, es la idea de obediencia. Por ejemplo, el consejo 941, correspondiente al segmento El Apóstol, señala:

> “Obedecer..., camino seguro. —Obedecer ciegamente al superior..., camino de santidad. —Obedecer en tu apostolado..., el único camino: porque, en una obra de Dios, el espíritu ha de ser obedecer o marcharse.” (De Balaguer 1939:133)

Si la obediencia ciega es camino de santidad, y la santidad es a su vez la meta a alcanzar, ¿cómo dudar de su importancia? Esta lógica es respaldada por el imaginario con el que Monseñor robustece la imagen de la obra, en donde sus miembros conforman una milicia o tropa. Al hacer de la obediencia una condición de santidad (obedecer o marcharse), el cuestionamiento y la duda sobre los procedimientos y premisas de la obra es un freno al correcto apostolado. Así, el consejo 936 decreta: “Al apostolado vas a someterte, a anonadarte: no a imponer tu criterio personal”. (De Balaguer 1932:133). 

En función de lo anterior, el enlace de elementos propios del orden tradicional y de un ethos económico moderno, no requiere de una explicación, no necesita ser justificado ni fundamentado. Por ejemplo, cuando en el consejo 208 se exalta la mortificación de la carne –“Bendito sea el dolor. —Amado sea el dolor. —Santificado sea el dolor... ¡Glorificado sea el dolor!” (De Balaguer 1932:29), respaldando moralmente el uso de artefactos para infringir dolor como los cilicios, no se espera una lectura crítica por parte del receptor, mucho menos un cuestionamiento a esta premisa que adquiere un carácter sagrado. En esta línea, la consideración 945 es tajante: “Es mala disposición oír la palabra de Dios con espíritu crítico” (De Balaguer 1932:133).

Ni el criterio personal ni el espíritu crítico son permitidos en el apostolado, por ende, no existe urgencia alguna por organizar racionalmente el disperso contenido moral que compone al Opus Dei. Los miembros que aspiran a un camino de santidad no deben cuestionar: "”Se me ha pasado el entusiasmo", me has escrito. —Tú no has de trabajar por entusiasmo, sino por Amor: con conciencia del deber, que es abnegación”. (De Balaguer 1932:141). Ya que no es un asunto de entusiasmo, y la motivación no es el motor, sino la conciencia del deber (nuevamente se recurre al imaginario militar para dar por cerrado un problema), toda justificación argumental al conjunto de prácticas de la obra están de más.

El dogmatismo es el pilar que configura de forma decisiva la cosmovisión del Opus Dei, permitiendo la convergencia de elementos tan distantes como el aquí llamado ethos económico moderno, y componentes diacrónicos (una visión estática –casi estamental– de la sociedad, la mortificación de la carne, o la aplicación sistemática de censura). Gracias al rol del dogmatismo, esta existencia paralela en dos mundos no es conflictiva, ni extraña. Ambos elementos se entrelazan sin la necesidad de parecer armónicos o coherentes, pues la obediencia y la postura acrítica son pilares fundamentales dentro del modelo de vida apostólico.  

## Conclusión

Al decidir darle curso a esta investigación, se cuestionó si existiría otra forma de analizar el Opus Dei. Una nueva viabilidad al estudio de este fenómeno fue dificultoso, debido, en primer lugar, a que gran parte de la literatura relacionada con el Opus analizaba a esta organización a través del poder o su vinculación directa e indirecta con el capitalismo, ya sea por medio de las teorías del trabajo o su relación con el mundo empresarial. Es en este sentido que la búsqueda llega a buen puerto cuando se recurre a investigadores e ideas que no aluden de forma directa el fenómeno religioso, pero que, no obstante, aportan suministros interesantes de aplicar en el área. Fusionando un abordaje más clásico a la obra desde su indudablemente llamativa conexión con el mundo del dinero, con conceptos tales como diacronía, se pretende abrir aquí una nueva veta de estudio: descubrir las estrategias discursivas que hacen del confuso ideario del Opus Dei algo macizo y de gran influencia. 

Teniendo en consideración aquellos elementos entendidos como diacrónicos (propios de una mentalidad de orden tradicional, anterior al advenimiento de los valores de la modernidad), y la complicidad y cercanía valórica del Opus Dei con el ethos económico moderno, se llega a la conclusión de que ambas dimensiones, tan lejanas y aparentemente inasimilables, cobran sentido en el discurso y las prácticas del credo mediante el influjo del dogmatismo: una unión que no requiere explicación. Si la obediencia es el pilar, y la duda algo a evitar, el concilio de ambas dimensiones no necesita ser argumentado, lógico, ni coherente. Es el dogmatismo quien permite que esta coexistencia no sólo sea real, sino también muy efectiva y progresivamente extendida. Este dogmatismo se constituye, principalmente, desde la articulación de una base conceptual sólida para la instauración de la religión misma: como se argumentó, el Opus Dei, en tanto organización religiosa sustentada en el tradicionalismo, articula las bases de su sentido en textos, imágenes y personajes que se encuentran fuera del mundo social: líderes santificados, escrituras sagradas, valores divinos, etc.; es decir,  idealismos metafísicos fuera de dimensiones al alcance de los hombres. Por consiguiente, estas fuente de sentido resultan inmutables, y la única forma de interacción posible es a través de las interpretaciones que pudiesen ser realizadas. Por medio de estas interpretaciones es que se concilia el pasado (tradición) con el presente (modernidad) a través del posicionamiento del credo en el tiempo diacrónico, una temporalidad paralela pero independiente del tiempo socialmente reconocido por las masas, que permite el distanciamiento necesario para la constitución de las bases de sentido extra-sociales que arman de cierta manera el conglomerado de creencias, prácticas, normas y valores que definen al Opus Dei. Así, la existencia de un tiempo diacrónico como un tiempo contrapuesto y diferente al tiempo de la modernidad otorga el emplazamiento que hace posible la existencia de grupos sociales como el Opus Dei que no se alínean a la cultura de masas ni a la ideología hegemónica de la sociedad, en base a la posibilidad de que el grupo social viva experimentando una historia-otra dentro de la diacronía, fuera de la historia general de su sociedad. En este punto es que la relación diacronía como un decir-respuesta frente a la sincronía (Maturano 2002:68) toma relación frente al concepto de tradición. Como ya fue explicitado, la relación que tiene la diacronía –en tanto tiempo paralelo y anterior– con la sincronía –en tanto tiempo presente y general– es una de intercambio desactualizado entre el pasado y el presente, donde la diacronía solicita una respuesta de reconocimiento proveniente de la diacronía, su “otro trascendente”, para identificarse como tiempo fuera del ritmo, así como también tiempo independiente. En la dimensión de las prácticas, también se realiza una dialéctica interaccionista entre la tradición y la modernidad, en el sentido de que los valores tradicionales (diacronía) y todos los demás aspectos sociales a ser aprehendidos por el grupo religioso deben ser reinterpretados hermenéuticamente desde la sincronía, ajustando esta importación tradicionalista para su apropiación por la institución situada en la modernidad. En este punto, la reinterpretación de la tradición se ve resignificada por los valores de la modernidad, y ajustada hacia una función utilitaria de cohesión social y constitución de una base de sentido que solidifique el vehículo diacrónico dentro de la modernidad misma, posibilitando finalmente la reunión entre el ethos económico moderno y los valores eclesiásticos tradicionalistas del Opus Dei en una sola institución social coherente con la modernidad. Lo valores modernos, entonces, dejan de aparecer contradictorios con los tradicionales, puesto que los tradicionales se ven situados fuera de lo socialmente alterable, volviéndose de esta manera en una base inalterable y sólo resignificable, que admite, en tanto hermenéuticamente adaptada, la añadidura de valores “líquidos” como los de la modernidad encima de este cimiento, puesto que son incapaces de alterar la base de sentido generada. La naturaleza del cimiento extra-social del Opus Dei es la clave de su esencia dogmática: en tanto el mundo se divide entre las esferas inconmensurables de lo sagrado y lo profano, aquello sagrado (visto desde la posición situada de un religioso comprometido) se ve imposibilitado de cuestionar o alterar lo sagrado (“La cosa sagrada es, por excelencia, aquella que lo profano no puede, no debe tocar con impunidad” [Durkheim 2010:36]), generándose la cohesión necesaria para el tipo de credo que es el Opus Dei, y la continuidad entre los tiempos pretéritos y modernos que puede unificar y realizar su complementariedad dentro de la institución religiosa.

A través del análisis de las obras de Escrivá de Balaguer, fundador y líder póstumo (pues continúa ejerciendo influencias a través de sus consejos), podemos entender la configuración de este imaginario, amalgama y mixtura religiosa. Por medio de sus palabras, se dirige la mirada de los fieles, se modela su conducta, y se persigue su obediencia ciega a los parámetros religiosos, sean cuáles sean. El apostolado en la vida ordinaria de Escrivá de Balaguer no remite gratuitamente a imágenes militares, pues su esencia está de igual forma en el obedecer, en lo incuestionable. El tramado detrás de la obra, se hila con aquello que no se puede contestar. Donde no caben las dudas, no hacen falta argumentos: he ahí la fuerza del Opus Dei.


## Referencias
-	Berman, M. (1988). Todo lo sólido se desvanece en el aire, la experiencia de la modernidad. Editorial Siglo XXI
-	Braudel, F. (2006). La larga duración. Revista Académica de Relaciones Internacionales, (5).
-	Calvino, J. (1967). Institución de la religión cristiana. Editorial de Literatura Reformada.
-	Corbiére, E. (2002). Opus Dei el totalitarismo católico. Editorial Sudamericana
-	Defez, A. (2000). Dogma, dogmatismo y escepticismo. Publicado en Muñoz, J. & Velarde, J. (eds) Compendio de Epistemología. Editorial Trotta 
-	Durkheim, É. 2010. Las formas elementales de la vida religiosa. Akal Editor.
-	Escrivá de Balaguer, J. (1977) Amigos de dios. Ediciones Rialp S.A.
-	Escrivá de Balaguer, J.  (1939) Camino. 
-	Gaymer, M (2005). La función ideológica del Opus Dei: la legitimidad de un orden social estratificado (Tesis licenciatura sin publicar). Universidad Alberto Hurtado, Chile.
-	Kant, I. (2010). Critica a la razón pura. Editorial Taurus
-	Meunier, B. (2002). ¿Por qué llegaron los dogmas? Revista  Théophilyon (7) 
-	Mönckeberg, M (2004) El imperio del Opus Dei en Chile. Ediciones Grupo Zeta
-	Smith, A. (1958). Investigación sobre la naturaleza y causa de la riqueza de las naciones. Fondo de Cultura Económica.
-	Weber, M. (1991). La ética protestante y el espíritu del capitalismo. Premia editora.
-	Ynfante, J (1996) Opus Dei, así en la tierra como en el cielo. Editorial hojas nuevas.
-	Bloch, E. (1982). Efectos políticos del desarrollo desigual (pp. 109–118). Buenos Aires: Amorrortu editores.
-	Hervieu-Léger, D. 2005. La religión, hilo de memoria. Barcelona: Herder Editorial.
-	Balandier, G. 1988. Le désordre, éloge du mouvement. Paris: Fayard.
-	Maturano, Á. E. G. (2002). Sincronía, diacronía y tiempo mesiánico. Génesis y evolución de la noción de tiempo en la fenomenología de Emmanuel Levinas. Enfoques, XIV, 57–71.
-	Saussure, F. de. (1945). Curso de lingüística general. Buenos Aires: Editorial Losada.

### Páginas web
-	http://www.es.josemariaescriva.info/articulo/amigos-de-dios (07/10/2014)
-	http://www.nocedal.cl/memoria/memoria_2009.pdf
-	http://mba.americaeconomia.com/articulos/reportajes/la-mision-la-red-de-escuelas-de-negocios-afiliadas-al-opus-dei


> Universidad Alberto Hurtado. Facultad de Ciencias Sociales. Escuela de sociología. Cátedra de Modernidad y Religión. 

> Profesor: Luis Bahamondes. Ayudante: Nelson Marin.

**Autores**: Felipe Larenas, Jacobo Matheu, Sebastián Muñoz, Bastián Olea.