project:
  type: website
  output-dir: docs

website:
  description: "Sitio personal de Bastián Olea Herrera"
  site-url: https://bastimapache.cl
  title: "Bastián Olea Herrera"
  favicon: profile.jpg
  open-graph: true
  twitter-card: 
    site: "@bastimapache"
  # image:
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Ahora
        href: ahora.qmd
      - text: Blog personal
        href: blog.qmd
      - text: Blog de análisis de datos y R
        href: https://bastianolea.rbind.io
    right:
      - icon: instagram
        href: https://www.instagram.com/raccunnie/
      - icon: tiktok
        href: https://www.tiktok.com/@bastimapache
      - icon: book
        href: https://www.goodreads.com/user/show/53224910-basti-n-olea-herrera
      - icon: twitter
        href: https://twitter.com

format:
  html:
    lang: "es"
    theme:
      - minty
      - brand
      - tema.scss
    include-after-body: goatcounter.html



