project:
  type: website
  output-dir: docs

website:
  description: "Sitio personal de Bastián Olea Herrera"
  site-url: https://bastimapache.cl
  title: "Bastián Olea Herrera"
  favicon: profile.jpg
  open-graph:
    locale: es_ES
  page-footer:
    left: "© 2026 Bastián Olea Herrera · [@bastimapache](https://x.com/bastimapache)"
    center: "[Inicio](index.qmd) · [Blog](blog.qmd) · [Blog profesional](https://bastianolea.rbind.io)"
    right: "Hecho con [Quarto](https://quarto.org), [R](https://bastianolea.github.io/aprende_r/) y [RStudio](https://posit.co/downloads). Sitio alojado en [Netlify](https://www.netlify.com/)."
  twitter-card: 
    site: "@bastimapache"
  # image:
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: R
        href: https://bastianolea.rbind.io
      - text: Ahora
        href: ahora.qmd
    right:
      - icon: instagram
        href: https://www.instagram.com/raccunnie/
      - icon: tiktok
        href: https://www.tiktok.com/@bastimapache
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/bastianolea/
  search: 
    location: navbar
    type: overlay

format:
  html:
    lang: "es"
    theme:
      - minty
      - brand
      - tema.scss
    include-after-body: goatcounter.html



