---
title: "Theodor Geiger. _Ideología y juicio de valor_ (1949)"
subtitle: "Ficha de lectura para el ramo de Sociología del Conocimiento"
date: "2014-05-29"
categories: 
  - "sociología"
---

Situaciones históricas puntuales desvirtuaron o bien alteraron el significado del término ideología, hasta darle el sentido negativo o incluso denostativo que actualmente posee. La definición de ideología entregada por Geiger corresponde a “ideas o series de ideas que no se corresponden con la realidad”, considerando que no existe una forma objetiva de caracterizar la realidad, y que por ende toda interpretación que se ofrezca respecto de ella tiende a ser falsa. Así, las ideas deforman una realidad supuestamente objetiva. Cada forma de pensamiento deformador de realidad proviene de un contexto histórico-social determinado, y por lo tanto existe una correspondencia respecto de cierta situación hacia cierto modo de «deformar» (o, mejor dicho, interpretar) la sociedad. De acuerdo a esto, una falsa ideología vendría a ser aquella que no se corresponda con la situación determinada del sujeto que interpreta (un A pensando como un B), pero calificarla como falsa no implica que exista otra ideología hegemónicamente real, sino que apunta hacia la ideología determinada correspondiente a la situación del sujeto. En este sentido, cada sujeto podría poseer una ideología correcta, por lo tanto sería imposible afirmar que una de ellas sea correcta para todos, sino que todos pueden alcanzar su propia ideología correcta atingente a su situación de vida. El conocimiento, según Geiger, reside en la formulación de proposiciones respecto de hechos verificables a través de observación o inferencia, y es en la concordancia entre conocimiento y realidad cuando se vislumbra la ideología. Cuando una ideología da una explicación de la realidad no totalizante ni unilateral, dicho conocimiento generado podría ser válido, o verdad (considerando que no ignora la determinación de dicho fragmento de verdad por parte de otras esferas del conocimiento o de la materialidad); pero cuando una fracción de verdad se muestra como la verdad completa, dicho pensamiento resulta falso. A este respecto, la generación de conocimiento puede recaer en ciertas ideologías, siempre que éstas sean sensatas con el método requerido y se atengan a lo estrictamente atingente. La ideología responde a la teoría, y el conocimiento a su vez responde a la teoría proveniente desde lo observable, por lo que se plantea que es incorrecto objetar los factores extra-teóricos de la ideología debido a que lo extra-teórico o ateórico es el tema principal de la ideología: criticar aquello que fue afirmado pero que no surge desde la teoría. Lo que no surge de la teoría es calificado de dicha manera puesto que se atribuye a factores no-materiales, lo cual remite a “sujetos suprapersonales”, ignorando que tanto las relaciones sociales como la sociedad misma es construida por sujetos. Pero, a la vez, la ideología también es calificada como ateórica por Geiger, dado que “toda teoría descansa en la teorización y objetivación de una relación afectiva primaria entre el hablante y un objeto” en tanto la ideología, aunque esté conceptualmente ligada a la teoría, trata de aspectos no teóricos como si lo fuesen. Es teoría aparente, y como falsedad, no atiene a las leyes de la lógica, y por ende su refutación se imposibilita. Se jacta de una objetividad que realmente no es más que apariencia ligada a su objeto determinado, puesto que la afectividad vuelve reales fenómenos que de no existir dicho lazo, serían meramente como aparecen según el conocimiento. 

Respecto a lo último: Geiger plantea que, en tanto los humanos tendemos cognoscitivamente a aprehender objetos de manera afectiva, y por ende a caer en la ideología, es aún posible romper con el sesgo respecto del conocimiento que se pudiese generar al exponer los temas a trabajar de una manera formal e histórica, y haciendo uso de un método cuasi-matemático que permita verificación y autocontrol. De esta manera convergemos con los procesos de teorización, formalización y distanciamiento de Mannheim. De lo anteriormente mencionado, destaca el autocontrol del investigador: un auto-análisis “existencial” interno de los lazos afectivos que pudiese existir, permitiendo “circunscribir el peligro de que mi pensamiento caiga en ideología respecto del objeto afectivamente ligado.” El distanciamiento de las propias afectividad objetivadas da lugar, entonces, a la posibilidad de un pensamiento pragmático y advertido respecto de las cargas ideológicas que pudiesen remover la facticidad del conocimiento remitente –de forma inevitable– a fenómenos afectivamente cargados.


###Referencias

- Geiger, Theodor. “Ideología Y Juicio De Valor.” Buenos Aires: Amorrortu editores, 1982, en Lenk, Kurt. “El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos.” Buenos Aires: Amorrortu editores, 1982.
- Lukács, Georg. “La Conciencia De Clase.” Buenos Aires: Amorrortu editores, 1982, en Lenk, Kurt. “El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos.” Buenos Aires: Amorrortu editores, 1982.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología del Conocimiento.

> Profesor: Juan Miguel Chávez. Ayudante: Nicolás Sanhueza.
