---
title: "Ernst Bloch. _Efectos políticos del desarrollo desigual_ (1962)"
subtitle: "Ficha de lectura para el ramo de Sociología del Conocimiento"
date: "2014-06-17"
categories: 
  - "sociología"
---

La función de la clase media en la producción corresponde sólo a un rol mediato; es decir, un medio entre los creadores del valor y los dueños de la propiedad, y en su condición no se ven remitidos a una cierta posición laboral de forma indeterminada –como sí lo hacen los proletarios, subyugados a la venta de su fuerza de trabajo, sino que comprenden ciertas expectativas de ascenso y movilidad. Aún así, la condición precaria del proletariado alemán se acentúa, pero esto sin verse traducido en un aumento de la movilización social de acuerdo a los pronósticos marxistas. La tesis del autor refiere a que el pronóstico no se ha visto cumplido en dicho momento histórico no por una falencia teórica del marxismo clásico ni por una imposibilidad de la praxis socialista, sino por efectos de la ideología en Alemania: las “fuerzas que disfrazan el hecho de su conversión (del proletariado) en mercancías” producidas por el desarrollo desigual. La conciencia de clase se vería mermada por la ideología: la falta de movilización no corresponde a un fracaso del marxismo, sino que es un indicador de su contingencia epocal, ya que desenmascara a la ideología. Estas fuerzas que afectan a la contradicción capital/trabajo nacen desde “factores antiguos”, que pueden ser remitidos al idealismo alemán que identificó Marx en La ideología alemana, en la cual el idealismo aparece explicitado como el producto de la experiencia de clase de los intelectuales (entre ellos los feuerbachianos y los jóvenes hegelianos), que se imprimía en la sociedad como verdad instalada, contraponiéndose a la experiencia objetiva del proletariado alemán y la visión materialista-histórica que se contrapondría a las experiencias ideologizadas. La ideología, para Alemania, correspondería a un segundo enemigo del pueblo visto desde el marxismo, puesto que podría analogarse a un velo que cubre las contradicciones patentes de dicha sociedad a través de la instalación de un discurso a-histórico y burgués que correspondería a un obstáculo frente al pueblo en búsqueda de una solución a su precariedad. Este idealismo que envuelve al pensamiento alemán en forma de ideología se vería explicado en las “supervivencias de un ser económico y de una conciencia más antiguos”, es decir, al atraso material de la “avanzada” política alemana denunciada por Marx en la Introducción a la Crítica de la Filosofía del Derecho de Hegel. Por lo tanto, el enemigo de la revolución ya no sería tan sólo el capital, sino que se enfrentaría ahora también contra a la ideología, en tanto ella imposibilita el avistamiento de la real contradicción determinante.

En este sentido, es posible realizar un enlace con las contemporáneas luchas feministas o ecologistas. Cuando unos pretenden dirigir todos los esfuerzos de lucha contra el Capital mismo, es inevitable que la lucha se bifurque contra todo aquel punto de contienda que corresponda a una invisibilización de la explotación por medio de la ideología, en tanto la victoria en dichas contiendas pondrá a vista desnuda los medios de acción de la burguesía para con la población. Entonces, para el autor la guerra imperialista se ve definida por factores anteriores y nacionales; es decir: la ideología. La esfera económica se ve determinada, así, en una segunda instancia, que resulta ser previa a la misma experiencia del capital. Bloch responsabiliza, en parte, a los factores precapitalistas, así como lo hizo Marx en el trabajo ya mencionado. “Esta determinación contribuye a la manifestación del nihilismo inherente a la ideología burguesa como un discurso doblemente mistificador”: mistifica la apariencia de la estructura económica y de sus productos una vez por el capitalismo, y una segunda vez por la ideología: “(la alienación) exhibe rasgos de una sobrevivida desigualdad de desarrollo doblemente «natural» y de una «naturaleza» sobrevivida doblemente mistificadora.” Los productos del desarrollo desigual aparecen para el autor como «historia no cancelada (…) prehistoria», abriendo paso a la búsqueda de una resolución a las contradicciones en juego.

Bloch construye el concepto de desarrollo desigual a través de lo interno y lo externo, interno siendo lo que no se adecua, y externo lo que no se encuentra en consonancia. Prosigue, que la clase media se encuentra en su situación de pauperización debido a su no-evolución respecto de los avances en los modos sociales de producción (en tanto su rol es, como ya se mencionó, mediato, y por ende responde al [y depende del] avance de los demás factores), y a la vez por un letargo de la historia, que se rehusa a ver a dicha clase como central o dirigente nuevamente por la naturaleza de su rol; así, se caracteriza a la clase media como una clase no-relevante para efectos del gran capital. Esta superestructura anacrónica, entonces, y a partir de esta no-admisión de la clase media, da paso al desarrollo desigual objetivo. La anacronicidad que se encuentra en el letargo y no-evolución de la clase media da lugar a una tercera forma de mistificación: el acatamiento de contradicciones diacrónicas por parte del capital otorgan un falso sentimiento de respuesta y actualidad para la clase media, cuando lo que ocurre realmente es una “distracción de las contradicciones estrictamente presentes del capital; utiliza(ndo) el antagonismo de un pasado todavía vivo como medio de división y de lucha contra el futuro que se anuncia dialécticamente en los antagonismos capitalistas.” Un caso contingente de esta distracción de las contradicciones podrían ser las discusiones que actualmente están tan en boga, que versan sobre reformas legales en torno a temas valóricos, como son el aborto o el matrimonio homosexual en Chile. Si bien ambos temas podrían remitir a la estructura nuclear de la familia burguesa, reproductores del orden social productivo, también podrían calificarse, a un nivel estructural, a distracciones por parte del capital y la burguesía respecto de la reforma última (abolición del capitalismo), ya que al dárseles respuesta a estas demandas a través de cambios legales o constitucionales, la sociedad –y en específico, la clase media– experimentaría un supuesto avance medible y destacable, que aparece como una “eliminación de los excesos del capitalismo”, siendo que de acuerdo a Bloch aquello correspondería a una distracción respecto de lo que realmente es necesario resolver: la contradicción primordial.

Estos ejemplos no se contradicen a los ofrecidos anteriormente (sobre feminismo y ecología), ya que los segundos (aborto, matrimonio homosexual) responden a soluciones inmediatas de problemas legalmente atados, mientras que los primeros (feminismo, ecología) responden a estructuras de dominación netamente ideológicas que abarcan mayor parte de la subjetividad a nivel social, en tanto dichos modos de pensamiento contaminan a todo nivel de interacción, mientras que las reformas mencionadas responden a casos concretos cuya solución recae en ente gubernamental y no en un cambio del discurso de la sociedad, como sí sería en el caso de la lucha feminista, por ejemplo, que no por la promulgación de leyes o la equiparación de sueldos ser verá superada, sino que su realización requiere del desmantelamiento de la estructura patriarcal y los valores que la sostienen (por lo que podría decirse que ocurre a la par de la revolución anticapitalista).

Las contradicciones sincrónicas ocurren en el presente, mientras que las diacrónicas corresponden a lo rezagado del pasado. La sincrónica incuba en el presente un futuro fruto de la contradicción misma, mientras que las diacrónicas son ahistóricas y no remiten a un futuro. La diacrónica, en tanto pasado, carece del proletariado, y atañe más a la clase media, y por lo mismo la sincrónica corresponde subjetivamente a la acción revolucionaria del proletariado, y se manifiesta objetivamente en un futuro inhibido (el producto de la revolución no-realizado); contrariamente la contradicción diacrónica trata objetivamente a un pasado no resuelto (las contradicciones distractoras). Esta contradicción diacrónica produce un furor contenido, que proviene de su relación difusa al verse entrelazada con la contradicción sincrónica, puesto que ésta trata las relaciones de clase y propiedad debido a su ligación con lo material y productivo (el proletariado), y por ende subyuga a la clase media (hija de la contradicción diacrónica), la cual entonces se conforma dentro del vaivén de la contradicción sincrónica como una clase sin historia, que por lo tanto carece de conciencia de clase auténtica. Esto provoca el fenómeno ya ejemplificado, donde la clase media “estalla solo respecto de lo extrínseco, de meros síntomas, y no se dirige al núcleo de la explotación”. Con esto se valida el ejemplo dado: cuando la clase media exige reformas, lo hace pensando en un cambio transversal, pero lo que hace es acotarse a lo aparente, lo sintomático, y nunca a lo estructural; esto producto de la ideología a-histórica (en el sentido de no-contingente a lo contemporáneo) y pretérita (en tanto remite a aquello sin solución de la sociedad pasada) que la configura.

### Referencias

- Bloch, Ernst. “Efectos Políticos Del Desarrollo Desigual.” Buenos Aires: Amorrortu editores, 1982. 109–118, en Lenk, Kurt. El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos. Buenos Aires: Amorrortu editores, 1982.
- Marx, Karl. “Salario, precio y ganancia.” 1898.
- Marx, Karl. “Introducción a la Crítica de la Filosofía del Derecho de Hegel.” Signo, 1898. 47–63.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología del Conocimiento.

> Profesor: Juan Miguel Chávez. Ayudante: Nicolás Sanhueza.