---
title: "La biografía cultural de las cosas: Aplicación sobre un objeto de uso cotidiano en su relación dentro de la contradicción mercado/cultura"
subtitle: "Ensayo para el ramo de Cultura y Modernidad"
date: "2014-12-02"
categories:
  - "sociología"
format: html
---

En el presente ensayo se analizará un determinado objeto –una bicicleta–  bajo la lente teórica de las postulaciones de Kopytoff (1991) en “La biografía cultural de las cosas: La mercantilización como proceso.”
Dentro del paradigma de la mercantilización propuesto por el autor, enmarcado en un afán biográfico de los intercambios económicos y los objetos sometidos a tales procesos, se identifica principalmente una tensión central: mercantilización contra singularización.

El argumento inicia desde una comprensión de la variedad de formas autónomas que pueden llegar a tener las estructuras de intercambio en las distintas sociedades (Kopytoff, 1991, p. 96). Una plétora de regímenes de intercambio de bienes han sido identificados en distintas culturas y épocas en el mundo, cada uno con diferentes jerarquías respecto de los bienes y su movimiento en los mercados. Bajo esta premisa, se plantea la existencia de sistemas culturales, los cuales, a través de operaciones clasificatorias en pos de esta jerarquías, son capaces de afirmar y reproducir las particularidades y diferencias en que las estructuras de intercambio se basan (Ibíd), en tanto generan valorizaciones respecto del flujo de mercancías entre individuos, normando su libre movimiento.

La forma particular de intercambio para las “sociedades avanzadas” (i.e. monetarizadas) se caracteriza principalmente por la presencia hegemónica de una tecnología del intercambio: específicamente, la existencia de intercambio equivalente basado en el valor de cambio a través de la mercancía-dinero, cuya existencia como potencialidad (en tanto tecnología) determina a su vez la necesidad de su máximo desempeño (Bauman, 2009), volviendo rápidamente a dicho sistema en el principal medio de intercambio disponible. Contrapuesto a este modo de intercambio, la única fuerza social que representaría una contraposición sería la «cultura» y «el individuo», validos únicamente por sus operaciones propias de clasificación, comparación, y sacralización, entre otras (Kopytoff, 1991, p. 116). En este sentido, se evidencia la existencia de una una construcción sociocultural frente a las apreciaciones de los objetos (Ibíd, p. 94), en el sentido del uso de herramientas de categorización por parte de la cultura, basada en los detalles biográficos de los objetos, en pos de construir juicios que den lugar a una percepción valorizada de las mercancías (Ibíd, p. 93). Así, “La cultura accede al orden separando, a través de la discriminación y la clasificación, distintas áreas de homogeneidad dentro de la heterogeneidad total.” (Ibíd, p. 96). Por lo tanto, es por medio de la categorización que se constituye tanto la igualdad como la diferencia en los objetos (Ídem), posibilitando la configuración de jerarquías ya mencionada. El autor plantea, en consecuencia, que la esencia de la cultura sería, así, la discriminación (Ibíd, p. 99).

Por otro lado, la mercantilización de la sociedad, inmanente al modelo económico dominante, significa necesariamente la equiparación general de los objetos vertidos al mercado (Ibíd, p. 95), en tanto todo aspecto del intercambio entre bienes se verá determinado por la propensión al intercambio de los objetos en tanto mercancías, viéndose éstas reducidas a su mutua y perfecta equivalencia por obra de la tecnología del intercambio: el dinero. Por lo tanto, se da una tendencia homogeneizadora del valor (Ibíd. p. 104), ya que el mercado opta por ignorar el valor de uso de los objetos en pos de un tránsito expedito dentro del mercado, facilitado por la equiparación de toda diferencia a través del dinero. Este principio de homogeneidad y equivalencia, entonces, resultaría opuesto a la naturaleza de la cultura, ya que el exceso de la mercantilización promovido por esta tecnología del intercambio inhibe e imposibilita la singularización de los objetos, la cual sería, según el autor, la tendencia general de los individuos en las sociedades no-avanzadas (i.e. no monetizadas). En otras palabras, la monetización de las sociedades genera efectos en las formas culturales de organización de los bienes y sus valoraciones en las sociedades otrora no-monetizadas, puesto que, en tanto la cultura –como ya se argumentó– resulta una especie de espejo de los modos productivos (un espejo afirmativo), un modo productivo que iguale y homogenice la producción total de una economía, dificultaría la configuración de jerarquías morales (Ibíd, p. 101), es decir, de grados de importancia socialmente adjudicada a los objetos, lo cual sería capaz de orientar a los sujetos en la configuración de sus identidades por medio de la construcción de valorizaciones regidas por biografías culturalmente transmitidas. En otras palabras, la existencia de un régimen que homogeneiza las mercancías imposibilita o dificulta la relación biográfica de un sujeto con un objeto, en tanto el objeto se ve removido de la carga cultural-histórica que su valor de uso y la valoración personal no-equivalente conllevaría.

Se evidencia, de esta manera, el conflicto mercado/cultura (homogeneización/singularización), al identificar el modo de operación de la estructura económica y de intercambio contra las pretensiones culturales de singularización de los sujetos. Son la cultura y el individuo los que se oponen a la homogeneización del valor (Ibíd, p. 104), dando la batalla contra la mercantilización de los objetos.

A partir del marco presentado, nos parece posible operacionalizar la presente teoría hacia el análisis de un objeto en específico. Como bien plantea Kopytoff, las biografías son siempre selectivas (Ibíd, p. 93), por lo que, y debido al rumbo que toma la argumentación del autor –ligado al ámbito económico-político de la naturaleza de los objetos dentro de un mercado de intercambio y las repercusiones culturales de tal posicionamiento– es que el análisis del objeto tomará pertinencia al relacionarlo dentro del lugar que pueda tomar en la economía de intercambio de bienes expuesta, identificando así las reacciones desde los distintos agentes involucrados en la teoría (cultura, mercado, individuo), así como su categorización final en la tensión mercado/cultura argumentado por Igor Kopytoff.

En este sentido, el ejercicio podría llevarse a cabo sobre un objeto tan cotidiano –pero a la vez personal– como puede ser una bicicleta. Una bicicleta resulta un objeto común para un ciudadano urbano promedio, de uso relativamente masificado, con una utilidad indiscutible e inmediata, pero a su vez de capacidades limitadas. Bien es una bicicleta una mercancía, en tanto objeto producido no por su valor de uso particular, sino que diseñado y construido en pos del intercambio económico; pero, ocurre que, durante el transcurso de la vida del objeto de análisis, ocurren ciertos movimientos que cambian esta situación, basados primordialmente en la relación servicial de este objeto en particular. Así, la bicicleta en cuestión no es, en el estado actual de las cosas, cualquier bicicleta: es mi bicicleta, la bicicleta que el autor de este texto utiliza como medio de transporte a diario hace aproximadamente 2 años. En este sentido, ya se evidencia un primer pre-paso de la operación de singularización: la bicicleta no es cualquier bicicleta, es una bicicleta con dueño.

La primera observación del objeto puede ser una genealógica, que explique la llegada de la mercancía al poder de su dueño. Esta aproximación abrirá las puertas al análisis biográfico del objeto. Si bien la bicicleta es un bien manufacturado de forma masiva, y por lo tanto a través de un complejo industrial homogeneizante y mercantilizador, la bicicleta en cuestión responde a una lógica parcialmente diferente, en tanto su obtención fue “de segunda mano”: Su compra se llevó a cabo en un taller de reparaciones de bicicletas de cercanía con la vivienda del comprador, vendida por un mecánico en particular que ayudó, enseñó y vio crecer durante toda su infancia al ahora dueño de la bicicleta. Ya aquí observamos otro hecho biográfico que valoriza a al objeto en su singularidad: en tanto la desmercantilización genera un quiebre entre lo mundano y lo común (Ibíd, p. 95), un intercambio que es mediado ya no por su equivalencia rigurosa de la mercancía (como en el resto de la economía), sino por un precio ideológico (influido por el capital social, los lazos involucrados, etc.), genera una desmercantilización del objeto, en tanto rompe con la homogeneidad propia de una mercancía vuelta equivalente, inscribiendo una primera nota en la larga lista de hechos biográficos que inscriben un objeto personal.

A través de los años, el objeto sufre un número de modificaciones: accidentes que significan el reemplazo de ciertas piezas, la incorporación de nuevas piezas por medio de regalos de amigos y (nuevamente) el mecánico del taller, adquisiciones que modifican la relación entre sujeto y objeto, y un par de capas de pintura amateur resignifican de una sola vez tanto física como subjetivamente al objeto, otorgan una nueva carga discursiva que ahora ya no es únicamente subjetiva (como fue el hecho de la obtención anormal de la mercancía), sino que será también en su forma manifiesta, al ser inscritos en el objeto unas determinadas situaciones históricas (materializadas en piezas y partes distintivas) que, más allá de representar mejoras cuantitativas en el desempeño del valor de uso del objeto, se vuelven marcas de singularización, que tornan única a esta bicicleta por sobre las cientos de hermanas que (probablemente) salieron de la línea de producción en un momento dado, específicamente por la relación biográfica que se construye con el dueño, con los individuos implicados, y con los sujetos que aprehenden la bicicleta en el día a día.

Esta bicicleta, pintada totalmente negra con pintura en lata opaca, cuyas ralladuras indican un uso exhaustivo (o bien una mala técnica de pintura), posee a su vez otras características como mercancía que la diferencian del resto. Es común escuchar entre ciclistas comentarios del tipo “si me subo a otra bicicleta, me siento extraño”. La relación servicial entre el objeto y su usuario da lugar a una hermenéutica constante con el objeto: los materiales comprometidos en el uso normal (y anormal) del objeto, la forma del objeto dispuesta por el diseño industrial que dialoga con la corporalidad del usuario, y la estética que se reconfigura y deforma con cada uso, vuelven de la bicicleta en un objeto cuasi-íntimo, que genera un lazo ya no sólo utilitario, sino de familiaridad y valoración subjetiva que determina a la bicicleta –en su relación con el dueño– en una bicicleta particular y propia, que se compatibiliza con una técnica personal que se actualiza con cada uso, y un repertorio de saberes (las “mañas”) que se interiorizan casi inconscientemente al momento de viajar en ella.

El objeto, otrora común y mercantil, ha adquirido una cierta “personalidad” para su propietario. Este acto –que se manifiesta quizás de forma más extrema en los ciclistas que incluso bautizan a sus bicicletas– podría ser entendido bajo el marco teórico expuesto como un «acto de sacralización» del objeto, que tiene como objetivo extraer desde la esfera de lo mercantil (Ibíd, p. 111) a un bien que se le han adjudicado nuevas características sensibles, volviéndolo en un objeto propio, especial. Es la mismísima manifestación de la contradicción homogeneización/singularización.

En las sociedades altamente monetizadas, argumenta Kopytoff (p. 117), el precio de un objeto se vuelve su valor, con un enfoque manifiesto hacia el valor de cambio, mientras que en las sociedades no-monetizadas (sociedades pequeñas, tempranas), el valor de uso es el que prepondera (por la ausencia de la tecnología del intercambio), así como también la inclusión de valoraciones locales, culturales, y biográficas (Ibíd, p. 118). Tal es el caso particular con la bicicleta: a pesar de identificarse su concepción en un complejo de homogeneización y mercantilización (la fábrica), la mercancía se ve resignificada en un mercado que podría considerarse “externo” del mercado ideal de las equivalencias (el mercado informal), rompiendo con la regla del valor de cambio que definiría a los sistemas de intercambio modernos, y acercándonos hacia los sistemas de intercambio premodernos (no monetizados). En estos mercados, la biografía cultural de un objeto sí es capaz de construir apreciaciones diferentes en los bienes de intercambio (Ibíd, p. 94), entorpeciendo el libre flujo de mercancías –que sería óptimo bajo la economía avanzada– al introducir la valoración subjetiva y personal de un objeto al momento de su intercambio. Pero, sumado a esto, y considerando que según el autor existen movimientos temporales que configuran las relaciones de propiedad (Ibíd, p. 90), una mercancía lo suficientemente singularizada por un sujeto puede bien dejar de ser una mercancía: “la misma cosa puede concebirse como mercancía en cierto momento, pero no en otro” (Ibíd, p. 89). Aquello sucede en el caso del objeto en cuestión: puede que el objeto sea cuantitativamente inferior a otros disponibles al poder de adquisición del propietario, pero la existencia de los rasgos biográficos comentados anteriormente inhiben tanto la propensión del propietario a intercambiar la mercancía (neutralizando así su calidad de mercancía, al sacarla de circulación), así como la posibilidad de que el propietario reemplace la mercancía por otra de mayor valorización. Cabe recalcar que esto no ocurre necesariamente en todos los casos, pero bien es el caso del presente trabajo.

Los actos sensibles de valoración biográfica de las mercancías truncan, entonces, el estado mercantilizado de ciertos objetos. Esto por la tensión entre el mercado y la cultura anteriormente vista, en la cual el individuo identifica y reproduce las categorizaciones que vuelven de un objeto en un objeto singular, en un ejercicio contrapuesto a la tendencia hegemónica de homogeneización mercantil del valor. La operación discriminadora de la cultura, por lo tanto, busca tomar posición en la instancia del uso de un objeto tal como la bicicleta, construyendo una relación biográfica subjetiva con el objeto que lo diferencia de otros. Esta operación no ocurre necesariamente con otros objetos (como una cuchara, una silla…), sino que, al parecer, es preponderante en aquellos de uso cotidiano o extenso, como una bicicleta, un teléfono móvil, un juguete, etc. Así, la teoría del proceso de la mercantilización de Kopytoff permite analizar las cosas desde sus relaciones con la esfera mercantil, al identificar cómo los objetos se acercan o alejan de la influencia mercantilizante, principalmente en torno a las configuraciones biográficas que hacen de ciertos objetos en más que meras mercancías, en un acto de desequilibrio y oposición con la circulación general de los bienes de intercambio en nuestra sociedad. En este sentido, la descripción y análisis de un objeto bajo la lente biográfica no recae en las particularidades físicas o fenomenológicas de los objetos, sino a través de los factores subjetivos que, sumados a los históricos, construyen un objeto alternativo: un objeto discursivo, con un valor diferente al de mercado, que versa sobre la relación sensible entre un objeto y su contexto, sus situaciones y vivencias.

## Referencias
- Bauman, Z. (2009). Ética posmoderna (pp. 1–26). Siglo Veintiuno Editores.
- Kopytoff, I. (1991). La biografía cultural de las cosas: Mercantilización como proceso. En La vida social de las cosas (pp. 1–18). México: Editorial Grijalbo.

> Universidad Alberto Hurtado. Facultad de Ciencias Sociales. Carrera de Sociología. Cultura y Modernidad

> Profesor: Luis Campos.