---
title: "El amor occidental como un concepto históricamente nacido y culturalmente reproducido"
subtitle: "Ensayo grupal para el ramo de Sociología del Conocimiento"
author: "Sebastián Adasme, Carlos Mackenney, Jacobo Matheu, Bastián Olea"
date: "2014-09-18"
categories: 
  - "sociología"
tags: 
  - amor
  - capitalismo
  - ideología
  - cultura
  - industria cultural
---

> El amor se concibe como un concepto netamente ideológico, en tanto resulta producto de condiciones históricas y materiales (productivas) relacionadas al surgimiento de la industrialización, que lo vuelven utilitario al capitalismo en tanto reproduce las normas y valores necesarios para la reproducción de dicho sistema. Este acto reproductivo ocurre a través de la aprehensión cultural del concepto por parte de la industria cultural, dando contenido simbólico a las prácticas. El amor, por ende, corresponde a un conjunto de prácticas social e institucionalmente instaladas, las cuales forman parte de un ciclo de retroalimentación entre la cultura y la utilitariedad que le da el capitalismo a ella. En términos simples, el amor se subyuga a los principios básicos del libre mercado, en donde, conceptualmente, el consumismo apropia dicho concepto y lo moldea en dependencia a las pretensiones lógicas de una cultura sumida en el consumo. 

Plantear el estudio del amor desde la sociología del conocimiento, en una aproximación de amor en tanto ideología, ha cobrado sentido desde mediados de siglo veinte. Luhmann (2012) ya daba luces a finales de los sesenta a través de un complejo análisis, dictando un curso sobre el amor como pasión, en el cual situó al amor enmarcado en una teoría general de los medios de comunicación, comparándolo con otros medios de comunicación tales como la verdad, el dinero y el poder, inscribiendo tal estudio en la línea de la sociología del conocimiento. Por su parte, Eva Illouz (2009) realizó un completo análisis respecto a la relación existente entre  amor y capitalismo, desde el cual se extraen nociones que permiten acercar aún más el concepto de amor como una ideología. Illouz pretende develar los efectos que ha tenido el capitalismo, y específicamente, el libre mercado, en la noción que tenemos en la actualidad respecto al concepto de “amor romántico”; en otras palabras, cómo –a través de sus diversos brazos– el mercado ha alcanzado a lo que significa lo propiamente relacional en la formación, constitución y consolidación de los individuos so pretexto del amor. Es decir, y en definitiva, observaremos como (a través de la mirada de Illouz), las diversas aristas que se desprenden del mercado (industria cultural, consumo, medios de comunicación, etc.), influyen de forma indefectible al momento de plantear, o replantearnos, la idea conceptual de amor romántico. Este replanteamiento se hace necesario desde la óptica de la sociología del conocimiento al identificarse la génesis histórica del mismo concepto de matrimonio, ligado íntimamente y de forma estructural al amor mismo (en virtud de un occidente industrializado); vertiendo luz en un concepto –el amor– que aparece como intrínseco al ser humano, en tanto forma parte de forma visceral en la vida social, pero que se devela como un concepto situado históricamente, hijo de ciertas condiciones estructurales que nos remontan al siglo XVIII. En dicha época empieza a brotar desde Europa el capitalismo como superación del orden feudalista, arremetiendo contra todas sus instituciones y reemplazándolas por aquellas funcionales al libre mercado; y producto de este cambio estructural, nuevos preceptos sociales reemplazan a los antiguos a modo de adecuarse a la vida industrial, individual y salarial que conlleva el capitalismo temprano. A través de ésta formulación, daremos respuesta a la interrogante investigativa: ¿cuáles son las implicancias del amor en tanto ideología en su relación con el mercantilismo actual?

El presente artículo pretende llevar la concepción del término “amor” a la esfera de la sociología del conocimiento; esto es, explorar la construcción de la ideología que conlleva el concepto. En primer lugar, se seguirán los postulados de Eagleton (1997), quien señala ideología como un proceso material general de producción de ideas, creencias y valores en la vida social, lo cual permite observar el amor como ideología desde el ámbito de su producción material, y desde su producción de ideas; ambas nociones serán abordadas desde su complejidad hacia una aproximación manifiesta en la sociedad actual. Comprender el amor como ideología desde la perspectiva de Eagleton conlleva identificar tantos las prácticas como instituciones del proceso material; si bien se puede bifurcar la ideología del amor, estos caminos se van interconectando constantemente hasta establecer un imaginario sustantivo de prácticas institucionalizadas del amor.

Las prácticas del amor que se pueden observar en la actualidad mantienen cierta esencia de las prácticas de siglos pasados, las cuales siempre han estado internalizadas en una suerte de cultura mediática; no resulta extraño considerar que en la sociedad el amor está subyacente como una lucha de poder, económico y cultural, en tanto se genera una construcción social del amor que emanan de dichos sistemas sociales. En este sentido, lo propiamente cultural, permeado a través del libre mercado por elementos tales como el consumo, la apropiación del concepto “amor” por parte de los medios de comunicación, la materialidad, entre otros, parecen ir moldeando la concepción propia del amor en virtud de los intereses intrínsecos del mercado en dependencia de la época o el momento cultural en el cual se vive. Es decir, el concepto de “amor romántico” parece no ser constante en sus predicamentos esenciales, sino que al contrario, sufre variaciones en virtud de cómo la sociedad (el mercado) reconstruye el concepto. En otras palabras, la idea del amor se especifica y varía en relación a cómo el mercado, a través de sus diversas manifestaciones, moldea el concepto, lo hace propio, y lo modifica en virtud de sus propias necesidades. 

La crítica a la Industria Cultural que heredamos de la Escuela de Frankfurt (Adorno y Horkheimer, 1994), permite dar un paso al costado para observar estas prácticas que están naturalizadas en el traspaso de nuestra intersubjetividad. Un claro ejemplo en el sentido de lo señalado anteriormente dice relación con las temáticas subyacentes a la mayoría de las películas y teleseries que se producen en Occidente, y que luego son replicadas en Chile. En estas se nos muestra una disputa sobre el amor bajo cualquier pretexto sensacionalista de subjetividades; estas representaciones cumplen el rol de enseñar el cómo se debe amar, de manera “práctica”, o bien la Industria Cultural promueve una praxis del amor, es decir que se obtienen sus significados desde la cultura, para luego volver a reproducirlas exagerando cada vez más los rasgos del amor como concepto, dando lugar a esta praxis del amor en una triada cíclica de cultura-mercado-prácticas. Sin embargo, estas representaciones parecen cumlir un rol cíclico en virtud del concepto de amor. 

En este sentido, la Industria Cultural adquiere sus predicamentos de base en la cultura, lo que posteriormente es ilustrado en un formato basado en la exageración para demostrar aquello que la misma cultura social devela en sus comportamientos relacionales. En las representaciones de la pantalla chica (y también en la grande) es posible establecer incluso un emparejamiento modelo de actores, como son los casos ejemplares del caso chileno con las duplas de actores Francisco Reyes y Claudia di Girólamo, o María Elena Swett y Jorge Zabaleta, los cuales se han encargado de transmitir las praxis del amor en un formato telenovelesco que queda registrado en el imaginario colectivo de los chilenos. Las escenas románticas que ellos interpretan, e incluso las historias de amor basadas en la imposibilidad de la realización del concepto amor y la significación netamente individualista de la relación y la institución que genera, quedan impregnadas en la sociedad a través del consumo mediático, generando la intención de ser replicadas en la vida real, donde la historia concreta de cada pareja rara vez adquirirá esa estética romántica de conflictividad. Es decir, se nos transmite constantemente una idea respecto al amor bastante idealista, en el sentido de que dichas relaciones posibles de identificar en estas producciones muchas veces cumplen con una estructura que raya con lo absurdo en cuanto a sus similitudes, y responde a una configuración de relaciones intersubjetivas utilitaria al orden social hegemónico (heteronormatividad, monogamia, institucionalización por contrato matrimonial, individualidad, etc.). De esta forma se preconfigura una idea respecto a como se debiesen plantear las relaciones amorosas entre los individuos. Sin embargo, la Industria Cultural no es sólo representación en pantalla. 

La sociedad de consumo está potenciada por lo que los grandes consorcios culturales pretenden naturalizar: no hay televisión y cine sin publicidad, y no hay publicidad sin productos innovadores que llamen la atención de consumo de distinciones. En este sentido, podemos observar en la actualidad que el consumo está presente en prácticamente todas las aristas en las cuales nos desenvolvemos socialmente. Es decir, el consumo es parte, lo queramos o no, de nuestras vidas, ya que se nos presenta de formas que muchas veces esconden su propio carácter. El amor en términos relacionales es un buen reflejo de esto.  Por otra parte, el consumismo, que incluso puede ser tratado como la última (o nueva) ideología del mercantilismo capitalista, se aferra a la Industria Cultural promoviendo esta praxis del amor, generando un círculo vicioso de una promoción del consumismo romántico de amor, donde este finalmente se transforma en técnica. Esta idea es particularmente relevante para el objetivo de este ensayo, esto es las implicancias del amor en tanto ideología en su relación con el mercantilismo actual, ya que en la actualidad pareciera ser que la forma en que llevamos nuestras relaciones amorosas se acercan bastante a una aplicación propia de un manual de instrucciones. Esto en referencia al hecho de observar la concepción del amor exactamente como las pretensiones del mercado quiere que tomemos en cuenta a la idea de “amor romántico”. Es decir que, por ejemplo, para cada acto realizado por un individuo A corresponde una respuesta típica de un individuo B. La esquematización e institucionalización de la idea del amor aparece como propia de la modernización de las sociedades. Esta modernización, por lo menos en el caso chileno, dice relación indefectiblemente con la instauración y arraigo social respecto a las ideas que predica el libre mercado. 

Pero, pese a este diagnóstico, si bien las personas pueden llegar a notar y manifestar la exageración telenovelesca de las prácticas del amor en un círculo consumista, esas mismas personas al sumergirse en estas prácticas olvidan, u omiten, este diagnóstico crítico. Esto muy bien lo señala Illouz: “en un marco de suspensión de la duda (necesario para la experiencia ritual) y de inmersión absoluta en las emociones del vínculo romántico, las personas pierden de vista el carácter consumista de sus propias prácticas y así reproducen (de modo inconsciente) el orden capitalista” (2009: 201). Y aún más, Illouz plantea, invirtiendo el análisis de Marx del fetichismo de la mercancía, un “fetichismo de las personas” en donde no es una mercancía que parece alienada de las personas que la produjeron, sino una persona que parece alienada de las propias mercancías que produjeron su experiencia. Por lo que las personas al experimentar las prácticas del amor estarán sesgadas por las mercancías que posibilitan su desarrollo romántico-amoroso.

La cultura mediática que promueve las prácticas del proceso material de la ideología del amor no se conciben de manera aisladas, es decir, no son sólo el consumismo promovido por la industria cultural lo que plasma un praxis del amor, sino que éstas van aparejadas a las instituciones clásicas, tradicionales, modernas o postmodernas del amor. Es así como la industria cultural promueve constantemente la institución del matrimonio, o más bien es el matrimonio quien institucionaliza a la industria cultural en el consumismo del amor romántico. En este sentido el matrimonio no es sólo esta institución antigua o hecho social total del intercambio entre tribus, sino que también es un mecanismo actual de promover consumismo heteronormativo.

Por un lado, la institución del matrimonio como una praxis del amor está relacionado a una reproducción de privilegios y clase, donde el capital social es puesto en juego en el mercantilismo amoroso. En la esfera del consumismo ya no solo podemos hablar de esta institución clásica o tradicional del matrimonio en tanto reproducción de clase y privilegios de estatus, sino que podemos ampliar a una noción moderna, e incluso posmoderna, del matrimonio como una estética pretensionista de sustento consumista; no es el privilegio de estatus social, sino el privilegio de la posibilidad de consumo que el matrimonio puede sustentar. 

Y por otro lado, la institución del matrimonio se presenta como la principal herramienta del amor como forma de reproducción del orden social; la imposición cultural del matrimonio se logra institucionalizando la heteronormatividad, produciendo una ‘familia productiva’ que se consume en el capitalismo mercantil. La heteronormatividad que produce las prácticas ideológicas del amor permite reproducir constantemente el emparejamiento de sexos opuestos, generando un rechazo en el imaginario de un amor entre personas del mismo género. Hoy, en el siglo veintiuno, tal imposición comienza tímidamente a desvanecerse, pero esto atenta contra la normalización del sexismo machista que reproduce la institución del matrimonio en tanto patriarcalismo, estando en la base de la industria cultural que reproduce la institucionalización de los valores. 

El matrimonio es, entonces (y para nuestra sociedad actual en tanto ideología, institución y momento histórico), la institucionalización de la ideología del amor como una relación de poder económico y cultural, donde subyace la heteronormatividad. Es, por así decirlo en el lenguaje sensacionalista-amoroso de la Industria Cultural, la historia de amor imposible entre un hombre y mujer que deben anteponerse a situaciones complejas que los grupos sociales promueven, impidiendo cada vez más la materialización de esa relación por un conflicto de pertenecer a grupos socioeconómicos distintos o ser partes de culturas donde se les prohíbe estar el uno para el otro.

Romper esta normatividad institucionalizada del matrimonio significa que es la misma industria cultural la que debe dar el primer paso, el cual se insiste que lo está haciendo tímidamente, replanteando el concepto del amor otorgando una mayor amplitud de género. Si bien esto pretendería disociar la heteronormatividad del amor impuesto por el matrimonio, las prácticas seguirían, aparentemente, asociadas al consumismo estético que promueve la industria cultural; aunque se amplíen los márgenes del amor, es la misma industria cultural la que realiza en su propio juego cíclico esta reasignación de valores, por lo que las nuevas concepciones del amor siempre estarán bajo el alero del consumo acelerado de distinciones. Incluso se puede plantear que, bajo la lógica del consumismo mercantil, existe todo un mercado por explorar y explotar al romper esta heteronormatividad.

Lawrence Stone, historiador británico, considera que esta nueva ligación del amor como base del matrimonio se trata de uno de los mayores cambios de mentalidad (mentalite) del último milenio de la historia de occidente (Stone, 1977, p. 4). Y cómo no, pues va de la mano con uno de los puntos históricos de quiebre más importantes de la historia humana: la revolución industrial. Los notables cambios en las relaciones de producción producidos por la revolución industrial entre los siglos XVIII y XIX en Europa conllevaron drásticas transformaciones en la ideología hegemónica, estableciendo una revolución de las subjetividades paralela a la revolución burguesa (Macfarlane, p. 3). El capitalismo mercantil, impulsado por los Estados-naciones más poderosos de Europa, requería erradicar las estructuras añejas que sostenían el orden feudal. Estas incluían leyes agrarias, relaciones de propiedad comunal, contratos laborales feudalistas, instituciones tradicionalistas o religiosas, entre otras; y en su lugar instalar la propiedad privada absoluta, la apertura de los mercados, eliminación de impuestos, la instalación del patrón oro, los contratos laborales de salario, la “liberación” de las naciones que no se alineaban al mercado, y más atingentemente a nuestro trabajo: la reformulación de las tradiciones, símbolos e instituciones que norman las interacciones sociales cotidianas. Como punto a tratar, nos referiremos a la institución del matrimonio basado en el amor. Esta forma de matrimonio era perfectamente aceptable para el capitalismo (Engels, p. 96), debido a que la complementariedad del matrimonio como un contrato libre con la naturaleza del capitalismo anteriormente mencionadas presentan una armonía que radica principalmente en la individualización de las relaciones interpersonales y las instituciones contingentes. “Cambiando todas las cosas en comodidades, (la producción capitalista) disolvió todas las relaciones tradicionales y heredadas y reemplazó el histórico y cronológicamente-santificado costumbrista derecho por compra y venta, por el ‘contrato libre’ ” (Engels, p. 96). El progreso por sobre las épocas anteriores, estipula Engels, respectaba a superar las condiciones contractuales heredadas, para dar lugar a los contratos voluntarios. En este sentido, el amor romántico materializado en el matrimonio por amor aparece como compatible con el ideal capitalista de antaño: romper a toda costa con las estructuras que imposibilitan al mercado; ya que él mismo representa un contrato entre sujetos libres, y su sola posibilidad nace desde este cambio de paradigma que es la revolución industrial: “El matrimonio de acuerdo a la concepción burguesa era un contrato, un asunto legal de negocios, y el más importante a ese respecto, porque decidía la suerte y la desgracia del cuerpo y espíritu de dos seres, de por vida.” (Engels, p. 96–97). El amor romántico, así, puede ser visto como un producto de la superación de las condiciones feudales por las condiciones capitalistas, y como tal, funcional y utilitario al mercado (Macfarlane, 1987, p. 4). La forma propia del amor de parejas casadas correspondería, entonces, al amor sexual tal como aquél vuelto costumbre por la contraposición de la cultura del caballerismo adúltero (Engels, 1908, p. 97), cultura que hace alusión a las costumbres colonizadoras de los Estados instaladores del mercado mundial. 

De acuerdo a lo anterior, nos percatamos de la naturaleza construida y utilitaria del concepto inicial de amor occidental. El amor resulta ideológico cuando observamos de dónde proviene: la experiencia que vivimos de amor no está exenta de influencias estructurales; es decir, no es el sentimiento gutural y natural que se suele considerar, sino que responde a una serie de prácticas –ya mencionadas en este trabajo– que otorgan un sentido utilitario al concepto, en tanto (1) el concepto surgió desde una adecuación social a las nuevas formas sociales de producción, las cuales exigieron de la sociedad una reordenación que permitiera la reproducción del capitalismo; (2) las nuevas formas de la sociedad normaron las interacciones sociales, desde la relación feudal hacia un ordenamiento individualista y de intervención mínima, donde la labor Estatal se remite al cumplimiento de contratos y de la sustentación misma del mercado (en tanto órgano puesto); (3) los valores y acciones resultantes reproducen y sostienen, a su vez, a la estructura capitalista; ya que si bien ella instó a que se desarrollaran los valores, es la sustentación de los valores a través de las interacciones sociales lo que permite que la máquina gire; es decir, el capitalismo como shock instaló formas de interacción que posteriormente se reproducen a través del capitalismo objetivamente instalado; (4) la cultura observa estos valores y los estampa, a través de la Industria Cultural, en obras mediáticas que sustentan, legitiman, instalan y reproducen los valores en forma de prácticas; es decir, observan aquello que es producto de las relaciones sociales de producción y lo materializan culturalmente, instalando los valores como ideas y símbolos en la cultura; (5) la cultura, posteriormente, devuelve a la sociedad al amor como una praxis, exponiendo el amor al servicio del capitalismo como simplemente “el” amor, instalando sus prácticas, símbolos e implicancias en el inconsciente, dando la vuelta entera al ciclo: el concepto proviene desde la lógica mercantil capitalista, es aprehendido por la cultura, y se reproduce hacia los sujetos que obtienen ahora prácticas y símbolos afines a la lógica mercantil, los sujetos a su vez actuando acorde a dichas prácticas, alimentando nuevamente a la cultura, y así sucesivamente, de forma cíclica. 

La acción, el concepto que otrora aparecía como vacío de intereses, y natural al individuo, se revela como construído en un momento histórico determinado y unas relaciones productivas dadas que imprimen en él prácticas y significados que reproducen dicho orden, lo cual es de sumo interés para aquellas instituciones estructurales que buscan reproducir y sostener el capitalismo como tal: la burguesía, englobando al empresariado internacional, las instituciones eclesiásticas, entre otros.

Ahora: Que el mercado se haya apoderado del “amor romántico” no quiere decir que el mercado, como ente mágico, haya creado el “amor romántico”, sino que las personas, basados en un sistema de libre mercado, lo han moldeado, simplificado, vendido, comprado y regalado como tal a través de la libre competencia. En ese sentido, si se piensa desde un sentido estrictamente liberal, las personas –bajo una racionalidad estricta– deberían ser aquellas que fiscalicen y acepten estas prácticas. Para Luhmann, el pensamiento anterior no debe ser visto como un beneficio extraordinario, ya que para él lo que pasa en el amor romántico sucede debido a que este es un medio de comunicación, por lo cual esto hace que algunos cambios que ocurren a nivel de sistema social no sean necesariamente posibles de asimilar por el individuo en tanto individuo. Lo anterior explica el estancamiento del amor en períodos prolongado de tiempo. En virtud de lo ya mencionado, analizar la formación del amor romántico de manera histórica tiene relevancia. Luhmann se detiene en aquel momento en donde “el motivo de rechazo, es decir, el no poder llegar a amarse, encontró una atención particular cada vez mayor” (Luhmann, 2008, p. 181). Su particularidad emerge del hecho “de que la familia seguía siendo considerada en el cambio de generacion como una unidad permanente y, por consiguiente, no se pretendía obviar la necesidad del matrimonio como fundación de una nueva familia, pero que debía ser controlado en calidad de reproducción de la familia.” (Luhmann, p. 181) En el transcurso de estos hechos la burguesía pudo oponer a la idea de “las buenas costumbres” de las capas superiores de la sociedad solamente el papel de dominio que debía tener el hombre en el matrimonio y la familia, por ende el sometimiento de la mujer. “Lo importante no era apurar los goces de la vida en las pasiones propias, sino el desarrollo de una solidaridad libre en el seno de un orden determinado. Y a esto corresponde la idea de un señor que ama su propiedad, es decir, su casa y sus bienes, a su mujer y a sus hijos” (Luhmann, p. 182).

Fue en Inglaterra en donde esta forma de generar “la vida en pareja” se vio en crisis, debido a que allí entró en controversia el predominio religioso-jerárquico del hombre. Desde un principio se defendió “la igualdad básica de los esposos y el fundamento del matrimonio en el amor, la razón y el respeto mutuo.” (Luhmann, p. 182) En este sentido, una familia que siguiera aquellos estándares sólo era posible por medio de un ente regulador, por tanto fue el Estado quien adquirió aquella lógica, dándose cuenta que con la regulación de la vida en pareja se podían generar condiciones más óptimas a la hora de legislar, por tanto “el concepto antiguo, y realmente lógico, de amar aquello que nos pertenece, perdió con ello su plausibilidad” (Luhmann, p. 183). Aquel proceso anterior Luhmann lo denominó diferenciación estructural, el cual crea, por su parte, la diferencia semántica “que da impulso a la evolución del código de las relaciones íntimas. En todo caso, éste es el fondo institucional, el único desde el que se pueden comprenderse la intensidad y el éxito literario de la nueva semántica del sentimiento.” (Luhmann, p. 183) Esto no quiere decir que el individuo no pueda hacer disfrute de su vida, sino más bien hace referencia a la fundación de instituciones cómo la familia, la educación y el matrimonio. El amor ya no queda supeditado a una representación de las cualidades corporales y morales, por tanto “el cambio no radica únicamente en que hace observables y descriptibles las situaciones, imágenes y oportunidades del amor; radica en su extensión y en su reducción.” (Luhmann, p. 185) Por otro lado, Luhmann señala “no nos forzaremos a considerar que se trata de un engaño de nosotros mismos acerca de lo que es el sentimiento ‘real’, sólo decimos que, de un modo u otro, en este tipo de interpretación de los sentimientos observamos efectos de largo alcance de la socialización cultural. No nos interesa su elaboración en el sistema psíquico, sino su función en el sistema social” (Luhmann, 2012, p. 58). Por lo tanto, desde la mirada de Luhmann, se dirá, en cuanto al amor, que la sociedad es la que tiene que disponer, en la institución del amor, de formas que faciliten el orden y la libertad de éste. 
Conclusión.

¿Es posible establecer dos tipos de amor: uno verdadero y otro falso?, o, dicho en otros términos: ¿en qué consiste la contraposición entre ideas, la disputa de puntos de vista respecto al tema del amor? El mercantilismo capitalista representado por la Industria Cultural pareciera inmiscuirse en lo que podríamos llamar un amor falso, la ideología del amor romántico basado en el utopismo de una relación estéticamente ejemplar. Pero ese pareciera ser el tipo de amor que se ha llevado a cabo como práctica social desde la misma emergencia del capitalismo. ¿Cuáles son lo motivos de su existencia? Es posible comprender las motivaciones subyacentes al tipo de amor romántico reproducido por la estructura económica, en tanto responde netamente a sus intereses de adoctrinación social necesarias a modo de reproducción del sistema productivo– he ahí la relación del amor con el mercantilismo: responde a una serie de prácticas culturalmente actualizadas que ve su gen creador en el cambio de paradigma feudalismo-industrialismo, y por ende en sus propios cromosomas comprende los valores más internos del capitalismo: contrato voluntario (comprende un negocio libre entre iguales), partes que deciden de forma independiente (actores no ven su racionalidad sujeta por factores externos, dejando el mercado libre), relación individual que no comprende otros actores externos (anulando la influencia de grupos externos en el flujo del mercado), se instituye legalmente como una herramienta de herencia de propiedad (reproduciendo el capital por medio de la herencia: parte fundante del capitalismo temprano), asienta la familia nuclear como órgano principal del mundo social (construyendo la familia nuclear como un fractal en lo que productivamente concierne, además validando la heteronormatividad), y finalmente la cultura toma el amor como práctica y lo vuelve prácticas de consumo, instituyendo tradiciones y procedimientos que responden siempre a interacciones inconscientemente mercantiles.


### Bibliografía

-	Adorno, T. & Horkheimer, M. (1994). Dialéctica de la ilustración. Madrid: Trotta.
-	Eagleton, T. (1997). Ideología: una introducción. Barcelona: Paidós.
-	Illouz, E. (2009). El consumo de la utopía romántica. España: Katz Ediciones.
-	Luhmann, N. (2012). El amor: el amor como pasión. Curso dictado durante el semestre de verano de 1969. Buenos Aires: Prometeo libros.
-	Luhmann, N. (2008). El amor como pasión: la codificación de la intimidad. Barcelona: Ediciones Península.
-	Mannheim, K. (2004). Ideología y utopía. Fondo de Cultura Económica.
-	Marx, K. (1968). La Ideología Alemana. Montevideo: Pueblos Unidos.
-	Engels, F. (1908). The Origin of the Family Private Property and the State. (E. Untermann, Trans.). Chicago: Charles H. Kerr & Company.
-	Macfarlane, A. (1987). Love and Capitalism. Oxford.
-	Macfarlane, A. (1987). The Culture of Capitalism. Oxford.
-	Macfarlane, A. (1979). History and Theory, Studies in the Philosophy of History (Vol. XVIII, pp. 103–126).
-	Stone, L. (1977). The Family, Sex and Marriage in England 1500-1800. New York: Harper & Row.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología del Conocimiento.

> Profesor: Juan Miguel Chávez. Ayudante: Nicolás Sanhueza.

**Autores:** Sebastián Adasme, Carlos Mackenney, Jacobo Matheu, Bastián Olea.