---
title: "Karl Mannheim. _Ideología y utopía_ (1987)"
subtitle: "Ficha de lectura para el ramo de Sociología del Conocimiento"
date: "2014-06-19"
categories: 
  - "sociología"
---

La ideología corresponde a una parte de la sociología del conocimiento. Esta sociología trata a la ideología no como mera mentira, sino que como una estructura total mental que determina las ideas en base a la situación histórico-social del sujeto. Según esto, los objetos aprehendidos por el conocimiento son interpretados de diferentes maneras de acuerdo al contexto, los intereses, y las “esperanzas, propósitos e impulsos que surgen de la experiencia” del sujeto (“marco”); por lo tanto, las ideas son determinadas por la estructura, lo cual implica tanto que el pensamiento se ve influenciado por factores externos a la teoría, y que el pensamiento carece de leyes inmanentes, sino que obedece a los movimientos de su entorno. Lo anterior demuestra una contraposición al «método antiguo de la historia intelectual» (también asimilable a la ciencia burguesa marxiana), puesto que al presentar las ideas de pensamiento existencialmente determinado instantáneamente se niega al conocimiento a priori, que plantea el conocimiento como dado y existente en su propio plano, separado de la realidad material. Aquí entra en juego la ideología, la cual se presenta como una verdad dogmática entregada por grupos divergentes en un campo de competencia para “conquistar el favor del publico”, dejando en manifiesto la tendencia a concretar lazos afectivos con ciertos objetos o ideas, que remueven la imparcialidad del pensamiento al verse el sujeto siempre tendiente a realizar actos de voluntad respecto de lo que debiese, en teoría, ser un acto empírico. 

Cada producto intelectual de determinadas características puede ser sólo engendrado bajo las condiciones históricas que permitan dichas características. Dichas condiciones históricas remiten principalmente a las condiciones materiales que determinan la vida den sujeto (i.e. su posición en la estructura social y política). 

Las expectativas del trato de un cierto análisis se ven determinadas, como ya se ha explayado, por la existencia social del sujeto; es decir, de la ideología inherente a su clase y posición social. El horizonte analítico, entonces, ve tanto su inicio como su fin de acuerdo a la ideología: (1) ve su inicio, porque las motivaciones afectivas que dan inicio al análisis provienen de la experiencia de vida bajo su posición individual respecto de las relaciones de producción; es decir, tanto la experiencia histórico-social, la experiencia individual y el momento histórico confluyen en la determinación del actuar y pensar del sujeto (en este caso un cierto análisis); (2) ve su fin, porque la extensión máxima de la cadena de conocimientos que se desarrolle mediante el análisis está destinada a colisionar con la barrera lógica de la ideología (principalmente política) del sujeto. Ya menciona esto Lukács en La conciencia de clase, planteando que la clase burguesa, si bien podría comprender y dar sentido a toda la extensión de la estructura económica desde su punto de vista situado, se ve imposibilitada de hacerlo, ya que aquello significaría necesariamente renunciar a su dominación –debido a que una acabada crítica de su posición resultaría en su autodestrucción (más sobre esto a continuación)–, y respecto del mismo tópico Mannheim plantea que la clase burguesa evita llevar a cabo un auto-análisis, puesto que se ha negado a «tratar histórica, concreta e individualmente los problemas sociales, por temor de que sus propios antagonismos internos (…) se pongan de manifiesto», dando –por el contrario– explicación a sus propias acciones e interpretaciones a través de un método «exclusivamente abstracto y teórico», por medio del cual evita dar un tratamiento empírico a los problemas que dan lugar a los mismísimos privilegios fundacionales sobre los que se construye su clase. Esta misma crítica puede trasladarse a la sociedad chilena, donde actualmente los sectores derechistas y “liberales” sitúan en su discurso principal y electoral la libertad de oportunidades, la libertad de elección, valores pacifistas y éticas humanitarias, todos éstos siendo tópicos gravemente contradictorios con la práctica histórica de los sectores derechistas chilenos, lo cual no les significa que su discurso pierda sentido para ellos mismos, en tanto su clase procura –como ya se mencionó– no realizar un análisis material-histórico de su trayectoria política y social hasta el momento presente, puesto que dicho análisis autocrítico desenmascararía su discurso actual como inconsecuente, y a su origen y reproducción de clase e ideario como ilegítimo.

Como se puede apreciar, la forma de proceder del sociólogo del conocimiento responde a ignorar la temática de la discusión para focalizarse en el procedimiento que da origen a las ideas esgrimidas durante el debate, pretendiendo identificar la base total del pensamiento del sujeto o grupo. Idealmente, las fuentes de incomprensión y choque lógico deberían poder verse suprimidas por el sociólogo. El análisis de la ideología, entonces, sería pertinente en el caso de una contraposición de ideas cuyos orígenes correspondan a existencias sociales diferentes que originen «incomprensiones fundamentales», porque de lo contrario desviar la discusión hacia la ideología no tendría sentido alguno, puesto que la incomprensión recaería en los términos conciliables.

El objetivo de la sociología del conocimiento, más allá de identificar el origen material-social de su ideología, es determinar el alcance y la extensión de la validez de dicha determinación, puesto que las determinaciones derivan a diferentes resultados «en cuanto los intereses y los poderes de percepción de las diferentes perspectivas están condicionados por las situaciones sociales en que surgieron y de las que dependen.»

La existencia social, como precepto principal para la identificación de la ideología a través de la sociología del conocimiento, permite depurar los discursos de afectividades ligadas a objetos e intereses subdiscursivos que son emitidos de forma cuasi-inconsciente, abriendo paso para una «discusión directa», llevando el conocimiento a un nivel de categorización más cercano a la empiria, en tanto idealmente terminaría refiriendo a una interpretación de fenómenos redimida de intencionalidades a-teóricas. Así, las relaciones del conocimiento aparecen en sus cualidades verdaderas en relación a la situación social, ofreciendo un enlace directo entre conocimiento y situación. Pero este enlace, de acuerdo a bases epistemológicas, debe establecerse como particularidad. Aquí surge una contraposición entre ciencias y epistemología, donde la epistemología otorga una estructura científica basal para la determinación de la verdad en tanto plantea el método según el cual la lógica y la filosofía se instituyen. En este punto Mannheim establece su crítica al papel hegemónico de las ciencias lógicas por sobre las ciencias sociales: así como el pensamiento del sujeto se ve determinado por el momento histórico, de la misma manera las ciencias y toda teoría se ven a su vez determinadas por la época, y por lo tanto ninguna ciencia puede adjudicarse válidamente el título de hegemónica o empírica. La sociedad se construye a través de relaciones materiales entre humanos, y por ende es sensato comprender que dichas relaciones provienen desde lo material y dependen de ello, de tal manera que la materialidad y la historia son padres de lo humano.


### Referencias
- Mannheim, Karl. “Ideología Y Utopía: Introducción a La Sociología Del Conocimiento”. México: Fondo de Cultura Económica, 1987.
- Geiger, Theodor. “Ideología Y Juicio De Valor.” Buenos Aires: Amorrortu editores, 1982, en Lenk, Kurt. El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos. Buenos Aires: Amorrortu editores, 1982.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología del Conocimiento.

> Profesor: Juan Miguel Chávez. Ayudante: Nicolás Sanhueza.