---
title: "Moral y legitimidad en el capitalismo moderno"
subtitle: "Ensayo para el ramo de Sociología Económica"
date: "2013-11-29"
categories: 
  - "sociología"
tags: 
  - capitalismo
  - hegemonía
  - moral
  - ética
  - legitimidad
format: html
---

En la actualidad, se suele aceptar al capitalismo como la única alternativa factible de desarrollo material global, a menudo ignorándose la base de legitimación que pudiese o no tener. La economía clásica considera un estado de naturaleza del ser humano que da a luz los comportamientos que permiten que el capitalismo de lugar a mercados que beneficien el común, pero dicho argumento cae al entenderse la moral humana no como innata, sino como producto de las relaciones productivas y económicas en las que se ve interno; en este sentido la hegemonía capitalista es la que permite en primer lugar que el error de la economía clásica ocurra, al instalarse por sobre otras formas económicas. La moral capitalista pasa por tres etapas: capitalismo moral (sustentado en instituciones y en la idea smithiana), capitalismo a-moral (deslegitimación de instituciones y prevalecimiento del Estado como ente moral) y capitalismo inmoral (corporativismo y extremización de la búsqueda por la ganancia se naturalizan). En su origen, el capitalismo entra como una aplanadora, destruyendo alternativas e instalándose necesariamente nivel global, lo cual lo hace radicar ilegítimo por el acto de dominación que esto implica, pero dado su trabajo de “molino satánico”, esta ilegitimación se oculta por fuerza, negándose e ignorándose otras formas de organización económica de la sociedad (el error de la economía clásica), posicionando al capitalismo como el único sistema capaz de satisfacer las necesidades de la sociedad, necesidades que él mismo plantea. Esta obra de hegemonización culmina con la solidificación de métodos de amarre que vuelvan a la sociedad civil dependiente del sistema mercantil; y la institucionalización del capitalismo como única opción política factible, acción que radica en el Estado y sus especiales facultades de uso de fuerza para evitar cambios. 

----

Si entendemos al capitalismo como un ente hegemónico y totalizador de la sociedad, es lógico también considerar que las interacciones sociales surgen desde él. Por lo tanto, el capitalismo debe poseer una moral, un conjunto de valores tanto incentivados como reprochados que den forma al intercambio y a las relaciones sociales. Generalmente se acepta al capitalismo como el sistema con la mayor capacidad de generar bien común, ignorando el razonamiento que puede llevarnos a dicha conclusión. En este sentido, no se duda de la legitimidad del sistema imperante, ya sea entendida como una legitimidad interna y actual, o bien como una legitimidad estructural, referente al inicio de su historia como sistema económico mundial. Se considera necesario, entonces, entender críticamente estas vertientes de legitimidad a modo de desambiguar la estructura histórica que soportó la globalización de los mercados, y a la vez ofrecer explicación y sopeso de la naturaleza hegemónica del capitalismo.

Para concretar estos puntos se recurrirá principalmente a diversos estudios respecto de la ética y moral capitalistas. Como pilar central se recurre a How Capitalism Lost its Soul: From Protestant Ethics to Robber Barons de Marie-Laure Djelic, de la escuela de negocios ESSEC (Francia), donde trata el legado de la obra de Adam Smith a través de Milton Friedman aplicando una crítica respecto del origen de la moral supuestamente inherente al sujeto sobre la cual se sostiene gran parte de la economía clásica, junto a inquirir respecto de las distintas etapas que atraviesa la ética del capitalismo dependiendo de las mutaciones de la sociedad y las instituciones que lo albergan; además del Is capitalism ethical? de Titus Suciu, de la Transilvania University of Braşov, quien realiza una reforma del modelo de Djelic y lo saca de su marco historicista para aplicarlo a la realidad moderna que observa tanto un avance del corporatismo capitalista como de la regulación e intervención ética del Estado en el mercado. Por otro lado, se sustenta el cuerpo argumentativo que pondrá en juicio la legitimación del capitalismo a través de los célebres estudios de Jürgen Habermas (Problemas de la legitimación en el capitalismo tardío) y Herbert Marcuse (El Hombre Unidimensional) los cuales desde distintas ópticas y ángulos tocan el aspecto hegemónico del sistema capitalista; así como Cómo leer El Capital de Etienne Balibar junto a Louise Althusser, El Capital vol. 1 de Karl Marx, Cuadernos de la cárcel de Antonio Gramsci y Class Alliances de Pierre-Phillipe Rey, quienes ofrecen el aspecto teórico de la dependencia entre clases y el sustento de la dominación capitalista por medio de la legitimación ideologizada. Karl Polanyi en La gran transformación enmarca todo el proceso de transformación de las sociedades precapitalistas al capitalismo, tocando los tópicos morales, legales y prácticos de dicha empresa. Para identificar dicha moral (o ética) capitalista, a también se presentan definiciones de dichos términos a través de Market Capitalism as Dispute Resolution: The Loss of Legitimacy and the Problems of the Welfare State de Walter Neale en la Association for Evolutionary Economics, con el fin de desarrollar una argumentación coherente respecto de el aparente estado de los aspectos valóricos del sistema.
	
Según Suciu (2009), la moral (del latín moris, virtudes) se define como un conjunto de formas de la conciencia social que regulan la cohabitación de personas en la sociedad (Suciu, 2009). Los valores fundamentales que gobiernan la sociedad, entonces, se ubican en la moralidad. La ética (del latín ethos, hábito, tradición), por otro lado, corresponde al grupo de normas que caracterizan lo correcto, lo positivo, lo exitoso, etc., en contraposición a lo condenable; además de significar el acercamiento teorético a la moral (Suciu, 2009). Así, entendemos moral como el grupo completo de regulaciones sociales implícitas, y ética como la fracción de valores cuya connotación deviene socialmente positiva y por lo tanto configura un espectro de acciones y posturas esperables y valorables.

Milton Friedman, en su defensa del libremercado como sistema social que garantiza bien común desde la acción individual siempre y cuando se le permita al mercado operar sin obstrucción alguna, cimienta la ética capitalista desde la base de una interpretación de Adam Smith, quien profesa «autonomía de la esfera económica y su precedencia moral e histórica sobre todas las demás esferas de la vida humana (Smith, 1776), en el sentido hegemónico del mercado.

El razonamiento liberal se basa, de acuerdo a Djelic, en que el capitalismo «funcionará a su capacidad óptima cuando los comportamientos individuales se mantengan sin restricciones y libres para explorar todos los caminos que dirijan hacia una maximización del interés propio, incluyendo cuando aquellos caminos puedan ser juzgados o sean no-éticos o anti-éticos» (Djelic, 2005, p. 5). Esta tesis es afirmada también por Friedman (1962), quien sostiene que las preocupaciones éticas debiesen estar ausentes de la esfera económica de manera que el mercado no se vea intervenido en sus dinámicas naturales. En una situación de mercado libre, el egoísmo de los individuos se vuelven, al combinarse en el mercado, en un orden de máximo bienestar común y abundancia.

Djelic (2005) critica como “milagroso” este argumento liberal acerca de la suma de conductas individuales a-éticas (sin ética) e in-éticas (de ética negativa) en un sistema colectivo de satisfacción del bien común, ya que implica que el mercado de alguna manera produce un orden moral (Djelic, 2005, p. 5). Por lo tanto, señala que el capitalismo se apoya en la argumentación liberal de un “mito fundacional” del ser humano, en el cual el hombre económico aparece como hombre natural, poniendo en segundo plano al hombre social, político o moral. Para Adam Smith, el carácter ético del capitalismo se erige desde una moralidad inscrita en cada individuo; es decir, la moralidad no es socialmente concebida, sino que proviene de los actores individualmente en tanto existe de forma innata, y por consiguiente se entiende la moralidad como una sola: la moral capitalista, del intercambio y la búsqueda del beneficio propio. Entonces, existe un estado de naturaleza del hombre –la división del trabajo, la competencia y la mano invisible–, sobre el cual sólo luego se inscribe el contrato social y político, como una reacción a la moral inherente al ser humano (Djelic, 2005, p. 3). De esta manera, un mercado libre producirá bienestar, y cualquier problema en alcanzar dicho bienestar económico provendrá de un mercado que no es realmente libre, que de alguna u otra manera está siendo regulado, limitado. Este último razonamiento que impulsa las ideas capitalistas modernas fue criticada como absurdo por Polanyi (1944), quien en La gran transformación plantea que «los liberales acusan a los factores más diversos de haber hecho fracasar (al libremercado). (…) El mito de la conspiración antiliberal (es decir, que busca regular y limitar los mercados) es, pues, común, bajo una u otra forma, a todas las interpretaciones liberales de los sucesos que acontecieron desde 1870 a 1890» (Polanyi, 1944). La falta de libertad para que el mercado opere en su forma natural, entonces, aparece como la excusa permanente de sus falencias y tropiezos en numerosas instancias históricas. Y dicha excusa se ha naturalizado en la actualidad hacia diversos ámbitos académicos (Djelic, 2005, p. 5), principalmente en la economía, fomentando reformas de corte neoliberal y de minimización del estado al rededor del mundo. El capitalismo, entonces, excusa siempre sus fracasos en diversos factores, aún habiendo tenido siglos de hegemonía mundial, no reconociendo sus errores estructurales y siempre insistiendo a la radicalización de su dogma. En este sentido, cabe poner en duda la legitimación que se adjudican los defensores del sistema para insistir en su viabilidad y calidad cuasi-divina de ordenamiento social.

Neale (1980), considera tres fuentes de la legitimación en los procesos sociales: (1) que el proceso sea inevitable, (2) que el proceso sea natural (y, por consiguiente, inevitable), y (3) que el proceso sea justo. Vemos cómo en el punto 2 se apunta hacia lo natural, siendo que lo natural en el capitalismo ha sido, como se mencionó previamente, construido de forma utilitarista a sus medios y objetivos, y hecho aparecer como natural. Esto fue ya expuesto por Polanyi, quien apela a la investigación etnológica para sostener el origen culturalmente determinado del objetivo del trabajo social, apoyándose en Mead (Polanyi, 1944), y que por lo tanto no existe tal cosa como una naturaleza humana que incline a los sujetos al intercambio mercantil. La “naturaleza” que dirigió los procesos de mercantilización a escala global y que entregó supuesta legitimación a su avance, entonces, surge desde una maquinación, una articulación institucional que construya una lógica de auto-legitimación. Por otro lado, la “inevitabilidad” no es necesariamente un punto que pudiese ser otorgado a aquellos que impusieron el libremercado a través de la historia mundial, pero si entendemos “inevitable” como “urgente”, sí, la colonización y la imposición del mercado por sobre numerosas culturas y formas de intercambio se realizó con particular “urgencia”, en tanto la división internacional del trabajo resultaba clave para la eficaz puesta en marcha del capitalismo a escala global (Polanyi, 1944). Respecto de la “justicia” del proceso… la expandida concepción etnocentrista durante las épocas de colonización y expansión del capitalismo claramente responden a un fenómeno histórico que, bajo su propia lógica anacrónica, resulta validador de la asimilación de culturas, sociedades, y medios sociales de producción, en tanto considera otras formas de vida como barbáricas (Taylor, 1993).

El capitalismo mercantil obtuvo su legitimación, según Neale, tanto desde fuentes naturales como morales, en tanto sus defensores han buscado hacer coincidir ambas categorías de legitimidad en las instituciones tradicionales de la sociedad burguesa (Iglesia, soberanía, jurisdicción, y legislación) (Neale, 1980), de tal manera que el mundo de la vida se muestre con una cohesión o lógica social que avale el modo social de producción. Pero ocurre que, paulatinamente, las instituciones se quiebran o pierden el grado de legitimación que otrora las volvió centrales, y se da que en la actualidad no existen agencias legítimas para establecer la lógica dentro de la cual el sistema de mercado adquiere sentido (Neale, 1980, p. 3). Esto se abordará más adelante.

En su forma moderna, el capitalismo genera un mundo más allá del bien y el mal, debido a que no se inscribe dentro de dicha distinción, sino que opera fuera de ella. La a-moralidad del capitalismo implica que la esfera económica se ve externa de la esfera social y ética, operando de forma independiente y des-afectada de dilemas morales, tanto positivos como negativos, en pos del libre funcionamiento de los mercados. Efecto de esto es el hecho de que al mercado no le importe si opera en una utopía liberal o en una dictadura latinoamericana (Djelic, 2005), sino que le importa cumplir su objetivo.

El capitalismo, a través su historia, ha adoptado diferentes formas y ha dado a luz variadas formas de organización social, por lo tanto es pertinente llevar a cabo un breve repaso histórico de las diferentes éticas que han soportado a dicho sistema. Suciu (2009) postula, a través de Djelic (2005), un modelo evolutivo de tres etapas acerca de los cambios en la moral capitalista. En la primera etapa, «capitalismo moral», el capitalismo se apoya en una lógica equiparable a la de la ética protestante weberiana, donde se suministran tanto refuerzos como castigos definidos por la tradición cultural, ofreciendo un enfoque en el refuerzo, significado en la ganancia monetaria como estimulante principal. Así, el interés económico imbuido por las normas morales determinan el comportamiento social. En esta etapa, la sociedad se ve estructurada por la moral económica, lo cual significa que el capitalismo cuenta con los medios para resolver desviaciones a la moral. Pero esta forma de organización se sostiene en la solidez de las instituciones morales de la época (iglesia, nobleza, etc.). En la segunda etapa, «capitalismo a-moral», la ética deja de provenir de las fuentes anteriormente mencionadas, ya que el incremento de la actividad industrial aumenta la población y la forma global de organización de la economía, dejando obsoletas las antiguas instituciones de orden social, las cuales empiezan a ser reemplazadas por formas democráticas de organización (Suciu, 2009). Entonces, la moral se desliga del proceso capitalista mismo, y empieza a residir en el Estado, en las organizaciones sociales; ocurriendo una ruptura de la idea de un capitalismo que genera bien común, para pasar a un capitalismo que únicamente actúa en el intercambio y que no tiene efectos morales. Esto se refleja en una división de las esferas públicas y privadas, en tanto en la etapa anterior se encontraban ligadas (ya que, supuestamente, el interés privado repercutía en el bienestar público). La acción de los sujetos se divide en consciente e inconsciente, debido a que las acciones económicas siguen repercutiendo en la dimensión ética, pero dicho acontecer aparece oculto. La tercera etapa es la de «capitalismo inmoral», donde la tendencia monopolista del capitalismo mismo se materializa, dando lugar a una sociedad corporativa, contraponiendo los principios de la democracia y los del capitalismo (la democracia busca el bien común, mientras que las corporaciones en el capitalismo buscan aumentar sus ingresos). La búsqueda de mayores ganancias por parte de los agentes económicos se vuelve una prioridad por sobre cualquier clase de institución o moral, radicando en una inmoralidad definitoria del sistema económico.

La búsqueda por la ganancia sin límites destruye, arrasa con todas las moralidades previas, por muy socialmente arraigadas que puedan encontrarse, en tanto el capitalismo instala su propia (in)moralidad del más puro estilo smithiano, pero lamentablemente sin las consecuencias que el “padre de la economía” advino, sino todo lo contrario: la ganancia se posa por sobre la solidaridad, el bien común, e incluso sobre la ley. 

Los mecanismos de producción capitalista, al absorber tanto los medios de producción mismos como la fuerza de trabajo del obrero, crea un lazo inseparable del trabajador al capital, en tanto remueve alternativas de posibilidad y vuelve el monopolio de los instrumentos de acumulación en funcionales al capital (Balibar y Althusser, 1965, p. 196). Siguiendo el racionamiento de Habermas, esta relación que se solidifica con el avance del capitalismo funciona como un “hilo invisible” que amarra al trabajador con la clase capitalista y viceversa; esto porque se vuelven, mediante el proceso hegemónico del capitalismo, en dependientes una clase de la otra.

Marx confirma, calificando a la clase trabajadora como un “subsidiaria del capital”, en el sentido de que el capital requiere que el trabajador vuelva incesantemente al trabajo productivo, y con dicho fin en mente desarrolla mecanismos para impedir al sujeto el escape del sistema, como por ejemplo, el consumo:

> “From the social standpoint, the working class, like every other instrument of labor, is a subsidiary of capital which, as the process of reproduction requires, entails within certain limits the individual consumption of the workers. Requiring that the worker return endlessly to work on his product and to bring it to the opposite pole, to capital, this process frustrates the efforts of its conscious instruments to escape it. Individual consumption provides, on the one hand, the means for maintenance and reproduction; on the other, it destroys the worker’s means of subsistence and so forces him to return again to the market for labor. The Roman slave was bound in chains; the wage laborer is bound to his owner by invisible threads. Only his proprietor is not the individual capitalist but the capitalist class.” (Marx, 1867, p. 574)

La clase capitalista se vuelve la propietaria de la clase trabajadora a través de los sistemas de posibilidad que ofrece (o limita), dando lugar a los “hilos invisibles” que generan una relación de pertenencia y dependencia entre ambas clases, instaurando una hegemonía que se manifiesta como argumento de legitimación de las relaciones sociales de producción, en tanto se comprende este círculo funcional que se presenta como única lógica instaurada como un deus ex machina que se vuelve ajeno a la historia, ajeno a la moral, por su propia cohesión interna. Pierre-Phillipe Rey (1982) apunta, siguiendo el proceso estipulado, a que son las relaciones de producción las que determinan la clase social, y no la clase la que es el sujeto de las relaciones de producción. Así, las formas de vida, los intereses y el espectro de posibilidad de los sujetos se consideran producto de las relaciones del producción (i.e., capitalismo en sus diferentes formas), refutando la noción liberal expuesta con anterioridad de que es la naturaleza del ser humano la que da lugar al intercambio capitalista. Marcuse condensa: “(el capitalismo) al satisfacer (las) necesidades (de los sujetos), perpetúa su servidumbre” (Marcuse, 1969, p. 12).

Esta forma de hegemonía se presenta prácticamente como una colonización de los modos de vida previos al capitalismo, donde se asaltan los modelos de intercambio y de trabajo, se anulan y se reemplazan por el intercambio mercantil y el trabajo asalariado. Polanyi menciona que «fue necesario ante todo destruir radicalmente el sistema social y cultural del modo de vida indígena», caracterizando dicho acto de dominación explícita como molino satánico (Polanyi, 1944).

Para Habermas (1984, p. 76), «(el capitalismo) ofrece una legitimación del dominio, que ya no es menester hacer bajar del cielo de la tradición cultural, sino que puede ser buscada en la base que representa el trabajo social mismo», esto por la relación de dependencia anteriormente mencionada. Continúa: «De ahí que el dominio político pueda en adelante ser legitimado “desde abajo” en vez de “desde arriba” (invocando la tradición cultural)», refiriéndose a la forma en que la hegemonía capitalista se reproduce por medio de la socialización de los valores y modos de acción inscritos en la acumulación de capital hacia el entero de la población; es decir, por la reproducción del “estado de naturaleza” liberal como base de acción para prácticamente todos los aspectos de la interacción social, sin necesidad de una coerción que vele por la dominación constante del sistema.

> “Sólo con la forma de producción capitalista, puede la legitimación del marco institucional quedar ligada de forma inmediata con el sistema del trabajo social. Pues sólo entonces puede el orden de propiedad trocarse de una relación política en una relación de producción, ya que para legitimarse puede apelar ahora a la racionalidad del mercado, a la ideología del justo intercambio, y no ya a un orden de dominación legítimo.” (Habermas, 1984, p. 77)

Cuando el orden de cosas que el capitalismo propone corresponde al orden político, en cuyo caso requeriría de una argumentación o exposición en pos de sopesar su factibilidad (así como cualquier otro proyecto político), la forma en que se presenta  (de forma intempestuosa, oportunista, prepotente) le permite posicionarse como relación de producción necesaria, inevitable, por lo tanto adquiriendo la capacidad de auto-legitimarse a través de una pretensión situacional o bien ideológica, siempre sacando provecho de su posición privilegiada en la escala social. A través de una exposición de sus capacidades sustentada por las mismas necesidades que genera, el capitalismo aparece como una alternativa factible para saciar el consumismo y el expansionismo mercantil, en tanto es él mismo quien aviva la consecución de dichos objetivos, y es a través de este movimiento de seducción que el capitalismo deslegitima (habiendo o no derrocado objetivamente) otras alternativas de modos de vida. «La racionalidad del dominio se mide por el mantenimiento de un sistema que puede permitirse convertir en fundamento de su legitimación el incremento de las fuerzas productivas que comporta el progreso científico-técnico», plantea Habermas (1984, p. 56). Entonces, el capitalismo se adjudica legitimación en tanto se presenta como el único sistema capaz de saciar las necesidades que él trae; es decir, tapa los hoyos que él mismo abrió, en términos coloquiales.

Tomamos, a partir de todo lo anteriormente expuesto, tres puntos: la auto-legitimación del capitalismo por medio de la instauración de una relación de dependencia entre clase trabajadora y clase capitalista, la a-moralización y posterior moralización negativa del capitalismo a partir de los presupuestos de comportamiento smithiano cuyos efectos utópicos no radican posibles, y la negación de cualquier posibilidad organizativa a partir de esta relación de dependencia, con sustento en una pseudo-colonización de otras formas organizativas, para obtener una conclusión respecto el tema principal del presente trabajo: las bases de la legitimación del capitalismo, y cómo éste radica dominante.

La lógica circular auto-legitimadora resulta coherente en la actualidad, cuando ya se consolidó tanto la necesidad como el método concernientes, y en este sentido considera una fuente válida de legitimidad en tanto responde de forma relativamente aceptable a demandas arraigadas en la sociedad, siempre y cuando se ignore que dichas demandas vienen de la mano de las soluciones. Así, al contar con la ignorancia que representa la moral liberal respecto del estado de naturaleza del homo economicus como piedra angular del modelo económico, el capitalismo aparece como un sistema total y completamente lógico, en tanto emanaría de las mismas tendencias innatas de los sujetos, y por lo tanto el mercado no sería más que un producto de la acción simultánea de los actores. Pero, como se argumentó anteriormente, este estado de naturaleza no es tal, sino que encuentra su génesis en la determinación económica de las interacciones sociales y la cultura en general, y en este sentido el capitalismo perdería su supuesta lógica inherente. Por lo tanto, el grado de legitimación que se le puede adjudicar al capitalismo depende del espacio temporal que consideremos para nuestro análisis. Tomando un marco temporal reciente, el capitalismo aparece como legitimado en tanto responde a las necesidades satisfactoriamente, pero si el marco temporal abarca la historia precapitalista, podemos ver cómo el juego fue arreglado, explicitando las conductas globalizantes, impositivas y opresivas a las que se recurrió para dar coherencia al sistema de mercados, tachando al proceso de inmoral y éticamente reprochable en tanto (de acuerdo a Neale, 1980) (1) el proceso no fue para nada inevitable, y de hecho respondió a específicos intereses de clase impuestos y no a demandas o posibilidades naturales de expansión o cambio; (2) el proceso definitivamente no fue natural en tanto comprendió un posicionamiento de un estrato como superior a otros, lo que significó una ruptura de los procesos individuales de cada sociedad y una alteración del balance de intereses locales; y (3) que el proceso fue injusto, ya que comprendió la intervención de agentes externos, la denominación de cierto grupos sociales como poseedores y otros como subyugados, e implicó sistemática dominación política, económica, militar, y cultural en el sentido de que se removieron y neutralizaron las instituciones locales para ser reemplazadas por otras, alienadas (ya hemos citado a Polanyi [1944] respecto de la característica incursión avasallante del capitalismo sobre los modos de vida anteriores a él. El capitalismo necesitaba «forzar a los indígenas a ganarse la vida vendiendo su trabajo», es decir, removerlos de su forma social de producción e impedirles continuar con su régimen de intercambio y organización social). Luego de este proceso, el círculo se cierra al generar determinadas metas funcionales al sistema económico, calificándolo de necesario por medio de la socialización de la ética smithiana, cuyo efecto envuelve todo aspecto de la sociedad en tanto se emplaza en la esfera económica (radicada monolítica, hegemónica).

Por lo expuesto, es posible concluir que el proceso de capitalización de las sociedades mundiales carece de legitimidad al efectuarse un análisis histórico. Sin embargo, el ejercicio de la dominación dentro del capitalismo existe y es socialmente aceptado; materializándose a través de las atribuciones monopólicas que se le adjudican al Estado, como lo pueden ser el control del ejercicio de la violencia, de la forma de gobierno, y de regulación de mercados, entre otras, todas siendo funcionales a la mantención del sistema en curso, reprimiendo, de esta manera, las posibilidades de cambio social al limitarse las oportunidades de acción política para los civiles y permitiendo al Estado anular cualquier intento de sublevación, llevando a cabo un proceso inverso al ya expuesto: la sociedad, por medio el Estado, genera los mecanismos para impedir cualquier cambio, sin importar que este provenga desde lo interno o lo externo, solidificando la hegemonía del capitalismo a través de poderes de máxima facultad.

### Bibliografía

- Suciu, T. (2009). Is capitalism ethical?
- Djelic, M.-L. (2005). How Capitalism Lost its Soul: From Protestant Ethics to Robber Barons.
- Friedman, M. (1962). Capitalism and Freedom.
- Neale, W. (1980). Market Capitalism as Dispute Resolution: The Loss of Legitimacy and the Problems of the Welfare State.
- Polanyi, K. (1944). La gran transformación.
- Taylor, C. (1993). El multiculturalismo y “la política del reconocimiento”.
- Gramsci, A. (1935). Cuadernos de la cárcel.
- Habermas, J. (1984). Ciencia y técnica como ideología.
- Smith, A. (1776). An Inquiry into the Nature and Causes of the Wealth of Nations.
- Balibar, E., & Althusser, L. (1965). Para leer El Capital.
- Marcuse, H. (1954). El Hombre Unidimensional
- Marx, K. (1867). Capital, vol. I.
- Rey, P.-P. (1982). Class Alliances.
- Marcuse, H. (1969). Un ensayo sobre la liberación.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología Económica.

> Profesor: Andrés Aedo.