---
title: "Por qué crearse un sitio web personal hoy en día"
subtitle: "Reivindicando los espacios digitales personales y una vida fuera de los algoritmos"
date: "2026-03-15"
format: html
categories: 
  - personal
  - programación
  - tecnología
---

Antes, la Internet era un lugar distinto. La gente creaba sus propias páginas, las personalizaban, Y crean comunidades en torno a intereses y experiencias de vida en común. 

Hoy, la Internet es un espacio dominado por grandes empresas, que nos ofrecen servicios gratuitos para tener una vida digital, pero con el trasfondo de utilizar nuestros datos y nuestro comportamiento para obtener beneficios económicos.

La Internet se caracteriza en el presente por la competencia de las distintas empresas y agentes económicos en obtener nuestra atención. Logran esto analizando nuestros datos para entregarnos contenido altamente personalizados, muchas veces generado automáticamente. Esto tiene la consecuencia de gobiernos con contenido personalizado, creando burbujas en las cuales se nos encierra. 

El contenido generado por estas empresas es minuciosamente diseñado para influenciarnos en los niveles más profundos la lucha por la atención y por la influencia ha derivado en el descubrimiento de que las emociones negativas suelen ser las que más nos movilizan a actuar. Por consiguiente, gran parte del contenido de las interacciones que vemos en Internet están diseñadas o son productos de la polarización, el odio, la humillación. 

Creo que las cosas pueden ser distintas. Podemos recuperar la Internet como un espacio de expresión personal, gobernado por nosotros mismos, usando muchas de las tecnologías abiertas que están disponibles. Por esto creo que es importante recuperar los espacios digitales personales, como éste. Esto nos permite salirnos del dominio de los algoritmos, y por consiguiente dejar de competir por atención, y dejar de alimentar las emociones negativas que suelen ser la estrategia del éxito.

Creo que podemos prefigurar una vida en la cual evitemos que las grandes empresas tengan el dominio de un aspecto tan importante de la vida social como es la digitalidad.

Actos tan sencillos como crear tu propio espacio, hacerlo tuyo, y contribuir para que los demás puedan hacer lo mismo.


https://www.linkedin.com/feed/update/urn:li:activity:7437596980849287168/

https://lisacharlottemuth.com/

https://lisacharlottemuth.com/bringing-everything-back-to-my-website

https://indieweb.org/POSSE

Publish (on your) Own Site, Syndicate Elsewhere