---
title: "Violencia sexual y de género en la dictadura cívico-militar chilena"
subtitle: "Ensayo para el ramo de Iglesia y Derechos Humanos en Latinoamérica"
date: "2015-11-24"
categories:
  - "sociología"
tags: 
  - dictadura
  - derechos humanos
format: html
---

La violencia de sexual fue uno de los tantos mecanismos de tortura utilizados por agentes de la dictadura en sus detenciones de obreros, estudiantes y militantes de izquierda durante el periodo 1973-1989. El Informe anual sobre derechos humanos de la Universidad Diego Portales afirma que la utilización de estas técnicas criminales no fue circunstancial, sino sistemática y constante, “muchas veces forman(do) un componente central de la humillación y deshumanización que sus perpetradores pretend(dieron) infligir” (UPD, 2014, p. 44).

Según el Informe de la Comisión ética contra la tortura (CECT) (2001) y Corporación de Promoción y Defensa de los Derechos del Pueblo (CODEPU), de todas las diversas técnicas de tortura aplicadas a las víctimas durante sus presidios —la mayoría de ellas aprendidas por los militares en extensas jornadas de formación castrense destinadas explícitamente a volverlos más eficientes en el arte de causar dolor extremo sin quitar la vida— las agresiones sexuales responden a un 4,5% del total.

El informe Valech informa que, durante la dictadura, se detuvieron en procedimientos policiales a 229 mujeres embarazadas; es decir, durante las acciones cotidianas de represión, los agentes apresaron este alto número de embarazadas, lo cual puede significar, por un lado, la alta participación femenina en organizaciones populares y de izquierda, o bien un sesgo por parte de las autoridades hacia el género femenino. De acuerdo al mismo informe, durante el periodo de 1978 a 1990, ocurre que 1 de cada 5 prisioneros políticos era, también, mujer. 

Un total de 3.399 mujeres dieron su testimonio a la comisión Valech sobre haber sido torturadas por agentes de la dictadura. Los números empiezan a tornarse borrosos cuando el mismo informe Valech debe procurar una sección completa para tratar la violencia sexual durante el régimen: La cantidad confesa de mujeres violadas sexualmente por sus captores desciende a tan sólo el 9,73%, una cifra que la misma comisión Valech y CECT se niegan a creer, adjudicando su baja tasa de confesión al duro proceso que significa, tanto para un hombre como una mujer, confesar el haber sufrido la experiencia del inhumano acto de la violación sexual. Aún así, desde este 9,73%, 11 de ellas se encontraban embarazadas durante su violación, un agravante que manifiesta la bestialidad de los crímenes cometidos.

El Informe CECT/CODEPU, presentado al presidente de la república Ricardo Lagos en 2001, resume las recurrentes torturas sexuales aplicadas como las siguientes: Violaciones (hombre, mujer, animal); Violaciones anormales (oral, anal); Violaciones individuales, colectivas, privadas, públicas; Introducción de objetos en la vagina; Introducción de animales en la vagina; Obligación de realizar actos sexuales en privado y en público; Manoseos y vejámenes sexuales; Aplicación de descargas eléctricas en órganos sexuales; Extirpación de órganos sexuales; Presenciar u oír violaciones de otros o de familiares.

En el informe Valech podemos conocer desgarradores testimonios de estos crímenes, contados duramente por sus víctimas: 

> Nos llevaban en camiones frigoríficos, amarrados, vendados, con capuchas… Me golpearon y aplicaron todas las formas de tormento: Golpes, corriente eléctrica, quemaduras con cera, cigarrillos; en un brazo aún tengo las marcas. Les dije que estaba embarazada, pero la verdad a ellos no les importó, al contrario. Me golpeaban con una fusta en el bajo vientre, para que perdiera mi guagua. Al tercer o cuarto día, comenzaron a violarme… varias veces me violaron y aplicaron corriente en la parrilla eléctrica… (ex-prisionera política de Tejas Verdes)

El embarazo como foco de la violencia de género vuelve a surgir en este testimonio, en el cual se asegura que los vejámenes y las golpizas iban intencionadamente hacia la zona del vientre. Producto de torturas como aquella, (según el informe Valech) 20 mujeres embarazadas sufrieron abortos producto de las violaciones y torturas sufridas.

> Fui violada, me ponían corriente, me quemaron con cigarrillos, me hacían "chupones", me pusieron ratas. Creo que estuve en [recinto secreto de la DINA], me amarraron a una camilla donde unos perros amaestrados me violaron. Estaba siempre con scotch, después una venda y después una capucha. (Mujer, 16 años, 1975, R.M.)

Lo chocante de este segundo testimonio no es simplemente el nivel de salvajismo absurdo al cual ciudadanos chilenos —otrora médicos, carabineros o militares— pueden llegar, aplicando tormentos inhumanos a sus compatriotas durante semanas y meses, sino la edad de la mujer torturada en cuestión: a tan solo 16 años, sufrió los peores vejámenes tan sólo por su afiliación política (lo cual ni siquiera es probable, en tanto 40,5% de los prisioneros políticos carecían de militancia, según el informe Valech).

¿Cuál es la importancia de recordar estos hechos macabros? Es sabido por el general de la población lo sanguinarios que fueron los agentes de la dictadura en propinar las mayores humillaciones y sufrimientos a los ciudadanos detenidos, con el objetivo de reducirlos a una miseria extrema en la cual pudiesen confesar el paradero de sus compañeros, afiliaciones, u otras informaciones destinadas a la sistemática eliminación ideológica del pensamiento de izquierda, pero aún así, poco es lo que se ha avanzado en materia de Justicia y Reparación. Al respecto, el Informe anual sobre derechos humanos de la UDP realiza la sorpresiva denuncia de que “en ningún caso, incluso cuando la violencia sexual infligida fue notoria, comprobada e incluso confesa por parte de sus perpetradores, ésta fue incluida en las condenas finales” (UDP, 2014, p. 44).


## Referencias

- Comisión Nacional sobre Prisión Política y Tortura. (2003). Informe de la Comisión Nacional Sobre la Prisión Política y Tortura (Valech) (pp. 1–534). Comisión Nacional sobre Prisión Política y Tortura.
- Comisión ética contra la tortura. (2001). Informe de la comisión ética contra la tortura al presidente de la república, Sr. Ricardo Lagos (pp. 1–121). Centro de Estudios Miguel Enríquez.
- Comisión ética contra la tortura. (2013). En la senda de la Memoria, los derechos y la Justicia. 1973-2013: 40 años de lucha, resistencia y construcción (pp. 1–216). Santiago: Editorial Quimantú.
- Universidad Diego Portales, Collins, C., Hau, B., Delgado, J. P., & Hernandez, R. (2014). ¿Una nueva medida de lo posible? Verdad, justicia, memoria y reparaciones posdictadura. In Informe anual sobre derechos humanos en Chile 2014 (pp. 21–62). Santiago: Ediciones Universidad Diego Portales.



> Universidad Alberto Hurtado. Centro Ignaciano Universitario. Curso de Formación General Teológica. Iglesia y derechos humanos en Latinoamérica

> Profesor: Boris Hau