---
title: "Georg Lukács. _La conciencia de clase_ (1923)"
subtitle: "Ficha de lectura para el ramo de Sociología del Conocimiento"
date: "2014-05-29"
categories: 
  - "sociología"
---

Para Lukács, la relación entre hombres sería la forma de conceptualización histórica más auténtica, ya que son los hombres los que producen tanto lo sensible como lo subjetivo. Lukács critica la concepción hegeliana de determinismo histórico a través de corporación suprema, notando que la tendencia histórica a plantear las voluntades humanas como determinadas a través de leyes trascendentales surge desde “la sumisión de los hombres de la sociedad burguesa a las fuerzas productivas”, la cual también es culpable de objetivar cada interacción hasta el nivel de imposibilitar la idea de una maniobravilidad de las relaciones sociales instituidas, pues aparecen como dadas. La resolución proviene de Marx, con su humanización de lo instituido a través de la materialización de las relaciones.

Se plantea una tendencia a la auto-objetivación de la sociedad al alcanzarse cierto nivel de progreso material, lo cual vuelve las estructuras postuladas validas sólo en el medio histórico en el cual se engendraron, removiendo en cierta medida el rol de la conciencia personal en el curso de la historia, pero a la vez otorgándole validez acorde al materialismo histórico, afirmando la posibilidad de cambio a partir de la conciencia, pero inmediatamente catalogando dicha conciencia como falsa, producto también del momento histórico en que surge. Así, si bien la conciencia tiene injerencia en la historia, la historia de todas maneras determina a la conciencia, por lo que el nivel de performatividad queda reducido a las posibilidades históricas. La crítica a la ciencia burguesa en este respecto radica en que la conciencia necesariamente es hija del proceso histórico, y nunca es una conciencia empíricamente dada, porque es producida por relaciones, las cuales al ser abolidas pueden desencadenar la supresión de la sociedad entera. Plantear lo contrario (el hallazgo de la empiria) es de hecho un ejemplo claro de ideologización. La conciencia del hombre, entonces, se presenta por el autor como determinada, y si bien en su determinación carecería de valor empírico, la situación histórico-social la validaría. Así, ciertos pensamientos sólo pueden surgir bajo ciertos momentos históricos considerando que los hombres aprehendieron su posicionamiento histórico-social. De aquí surge una definición de conciencia de clase: si es que existen –como se plantea– pensamientos adecuados a una situación objetiva; es decir, pensamientos que surgen y se ven validados lógicamente por su contexto, entonces corresponderían a pensamientos nacidos desde el posicionamiento respecto del proceso productivo, “y la reacción racionalmente apropiada que de esta manera se imputase a una situación típica determinada dentro del proceso de producción sería la conciencia de clase.”

Según Lukács, sólo las clases sociales capaces de “percibir la totalidad de la sociedad actual en general” corresponderán a clases capaces de intervenir en el curso de la historia. Las clases incapaces de comprender la estructura económica de la sociedad desde su posicionamiento ideológico se remitirán a meramente oscilar entre las clases dominantes o revolucionarias. En este sentido, podríamos plantear que en la actualidad, la clase media se vería imposibilitada de «retardar o apresurar el curso de la historia», en tanto carece de un contexto que le permita experimentar las partes que conforman la estructura societal, en tanto no participa –por definición– ni de la producción ni de la posesión de propiedad productiva o poder alguno, puesto que su ubicación en las relaciones de producción es meramente mediato. Ya que sirve sólo como intermediario desde un polo de la economía al otro, carece de la comprensión para identificar su propia situación, y carece de capacidad de organización (por la diferencia y poca definición de intereses), discurso común (por la división del trabajo), e intereses compartidos (nuevamente por la división del trabajo, y por el bajo compromiso entre trabajador y oficio), y por ende se ve destinada a lo elemental, superficial, y carente de meta.  De acuerdo a lo planteado, la clase burguesa, según Lukács, comprende todos los presupuestos para que aprehenda un entendimiento cabal de la sociedad completa desde su punto de vista, pero dicha conciencia prontamente se vuelve falsa, ya que, de acuerdo a su «propia situación de clase» y su situación objetiva en la producción, puesto que debe negarse a sí misma al entender su propia organización, ya que una resolución total de los problemas de la estructura económica requieren necesariamente “traspasar los límites del capitalismo”.

## Referencias

- Lukács, Georg. “La Conciencia De Clase.” Buenos Aires: Amorrortu editores, 1982, en Lenk, Kurt. “El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos.” Buenos Aires: Amorrortu editores, 1982.
- Bloch, Ernst. “Efectos Políticos Del Desarrollo Desigual.” Buenos Aires: Amorrortu editores, 1982, en Lenk, Kurt. “El Concepto De Ideología: Comentario Crítico Y Selección Sistemática De Textos.” Buenos Aires: Amorrortu editores, 1982.

> Universidad Alberto Hurtado. Carrera de Sociología. Sociología del Conocimiento.

> Profesor: Juan Miguel Chávez. Ayudante: Nicolás Sanhueza.