---
title: "Sobre el acceso a los testimonios y documentos secretos de las comisiones"
subtitle: "Ensayo para el ramo de Iglesia y Derechos Humanos en Latinoamérica"
date: "2015-11-24"
categories:
  - "sociología"
tags: 
  - dictadura
  - derechos humanos
format: html
---

Las amplias y ricas informaciones documentales y testimoniales recolectadas por las comisiones «de Verdad y Reconciliación» (Rettig), «Sobre Prisión Política y Tortura» (Valech I) y por la «Comisión Asesora Presidencial para la Calificación de Detenidos Desaparecidos, Ejecutados Políticos y Víctimas de Prisión Política y Tortura» (Valech II), se sustentan sobre un criterio basal de secreto y privacidad, amparado por la ley 19.687 “que establece la obligación de secreto para quienes proporcionen información conducente a la ubicación de detenidos-desaparecidos” (INDH, 2014, p. 280). Este criterio se concibió a través de la Ley 19.992 (promulgada el año 2004) como una forma de garantía para las fuerzas armadas y agentes del Estado —similar en cierto grado a la Ley de Amnistía— para que éstos pudiesen entregar informaciones respecto del paradero de víctimas e informaciones afines bajo un criterio de confidencialidad que no les fuese excesivamente perjudicial al momento de declarar, colaborar, o bien participar en juicios; pero también como una medida básica de protección de la identidad de víctimas y sus familiares, manteniendo en privado informaciones sensibles, dolorosas, traumantes, o que quizás pudiesen ser usadas en sentido punitivo.

En la práctica, lo que esta regulación al acceso a la información significa es que todos los documentos, antecedentes, materiales e informaciones recolectados por las diferentes comisiones de Verdad y Justicia, son en última instancia de carácter privado y secreto, exceptuando los informes que dichas instituciones hayan publicado (Ibíd, p. 281). El periodo de secreto bajo el cual se rigen dichos documentos se extiende a los 50 años desde su fecha de obtención, según el artículo 15 de la ley 19.992, luego de los cuales dicha información pasará a ser pública. En el intertanto, los documentos han sido custodiados por el Ministerio del Interior, fuera de los ojos de ONGs, organizaciones de derechos humanos, o centros de estudio, e incluso del Poder Judicial.

La única salvedad a esta privación al acceso a la información, es que la misma sea solicitada por los mismos individuos que hayan generado los testimonios. Esto aparece en el tercer párrafo de la ley 19.992, donde se expresa: “ninguna persona, grupo de personas, autoridad o magistratura tendrá acceso a lo señalado en el inciso primero de este artículo, sin perjuicio del derecho personal que asiste a los titulares de los documentos, informes, declaraciones y testimonios incluidos en ellos, para darlos a conocer o proporcionarlos a terceros por voluntad propia.”

A propósito de esta salvedad que hace la ley, el artista visual Francisco “Papas Fritas” junto a su equipo y la Coordinadora de Santiago de Ex-Presas y Presos Políticos del MIR, inauguraron recientemente una iniciativa de “desclasificación popular”, en la cual se distribuyeron manuales para que ex-presos políticos pudiesen llevar a cabo, bajo la ley 19.992, una desclasificación de los documentos amparados en las distintas comisiones que les resulten pertinentes. Esta iniciativa buscaría solucionar, mediante la participación voluntaria de víctimas de violencia política que hayan entregado su testimonio frente a la comisión Rettig o Valech, el problema del secretismo de la información, con un enfoque de divulgación de los crímenes, y de trabajo en pos de una justicia más inmediata y directa frente a los criminales aludidos en los informes.

El informe del INDH, al referirse al acceso a información y consecución de justicia, cita a la declaración universal de los derechos humanos, la cual en su  artículo 19 contiene el derecho a “investigar y recibir informaciones y opiniones, y el de difundirlas”, mientras que los Principios de Johannesburgo (principios internacionalistas incorporados a estándares internacionales para la protección de la libertad de expresión y el acceso a la información pública), por su parte, señalan que “ninguna restricción sobre el libre flujo de información podrá ser de tal naturaleza como para estorbar los propósitos de los derechos humanos y el derecho humanitario” (Ibíd, p. 275). Lo que ocurre es un incumplimiento de ambos tratados, en tanto se ve vulnerado el derecho a investigar abiertamente los únicos documentos oficiales existentes, dejando en la oscuridad de las bóvedas del Ministerio del Interior a los responsables de la perpetración de tantos crímenes de lesa humanidad; y por otro lado se incurre en una restricción al acceso a información clave para llevar a cabo justicia en casos de violación de derechos humanos.

No obstante, hay que considerar el contexto en el cual se tomaron las medidas anteriormente criticadas.  A pesar de haberse diseñado luego del año 2000, las leyes 19.992 y 16.687 (que establece la obligación de secreto para quienes proporcionen información conducente a la ubicación de detenidos-desaparecidos) (Ibíd, p. 280) —entre otras— debieron ser concebidas, dentro de lo que fue (y es aún) la transición pactada hacia la democracia, con un especial enfoque de suavidad e impunidad frente a las instituciones que heredaron el poder de presión de la dictadura: las fuerzas armadas, de inteligencia, y carabineros. Fue necesario prometer, en cierta medida, ciertos niveles de seguridad para “garantizar información proveniente de los institutos armados y de exagentes del Estado, conducente a ubicar los restos de las víctimas de desaparición forzada” (Ídem). Es decir, lo que se llevó acabo fue un intercambio de sus confesiones, testimonios e informaciones, a cambio de un cierto nivel de seguridad, anonimato, y —por ende— impunidad para las partes que decidían colaborar (UDP, 2014, p. 51).

Pero nuevamente, y en base a estas informaciones, surge un problema de coherencia: ¿Es o no el deber del Estado esclarecer verdad y ofrecer justicia en los casos de violaciones a los derechos humanos? Y, de ser así, ¿entonces por qué se esperan las querellas personales de las víctimas y sus iniciativas para liberar información otrora confidencial, y/o los testimonios voluntarios de los criminales impunes organizados al rededor de pactos de silencio, en lugar de realizarse investigaciones inquisitivas independiente de la presión (o falta de ella) por medio de la contraparte, haciendo uso del poder Estatal para encontrar la Verdad? 

Dentro del proceso de obtención de verdad y justicia respecto de los crímenes cometidos durante la dictadura cívico-militar chilena, parecieran colisionar dos funciones del Estado: la protección de víctimas y confesores a través de su derecho a la privacidad de sus testimonios, y la obtención de testimonios verídicos y suficientes para esclarecer las condiciones y contextos de los crímenes en pos del suministrar justicia a quien sea debido. Este problema de colisión de prioridades fue denunciado por un número de diputados a través de la Legislatura 362ª (martes 23 de septiembre de 2014), donde se plantea que la convivencia entre tres aristas en el proceso posdictatorial de establecimiento de verdad (verdad, justicia y reparación) las cuales, en tanto individuales, poseen un valoraciones distintas que pueden sobreponerse dependiendo de los intereses de los órganos superiores (Boletín N° 9598‐17, 2014, pp. 138-139). “Es esta concepción la que permite explicar el secreto establecido respecto a los antecedentes obtenidos en el funcionamiento de la Comisión Valech, pues priorizándose por el establecimiento de la verdad y de la adecuada reparación de las víctimas, se deja en un segundo plano el establecimiento de la justicia (…) el establecimiento de este secreto finalmente consagra a nivel institucional la impunidad, en cuanto impide que estos antecedentes puedan ser conocidos y calificados por los Tribunales de Justicia.” (Ídem).

Entonces, pareciera que el Estado debe definir de una vez sus prioridades, y sacrificar la importancia de alguno de los tres componentes (Verdad, Justicia y Reparación) a la hora de llevar a cabo el proceso. Optar por la Verdad (1) necesariamente pasará por sobre la Justicia, en tanto que significará —en parte— la revelación de documentos secretos que contienen acciones, conexiones, y hechos personales e institucionales incómodos y punitivos para muchos, y realidades crudas y humillantes para otros, pasándose a llevar así algunos derechos y privacidad en pos de una Verdad clara y plena; mientras que optar definitivamente por la Justicia (2) puede significar un proceso lento y tortuoso como el actual, puesto que se deben considerar todos los conductos regulares y legales —ineficientes y sesgados— para la obtención de testimonios y la impartición de condenas (incluyendo la obediencia a decretos y leyes dictatoriales injustos, pero legales al fin y al cabo), producto de lo cual muchos de los criminales están falleciendo impunes, sin conocer el peso de sus horrendas acciones, o bien víctimas y familiares fallecen sin haber conocido el paradero de sus seres queridos o sin haber visto a sus torturadores y captores pagando sus crímenes; y por otro lado, la Reparación (3) puede también conseguirse sin haber alcanzado la Justicia (3.1), frente a lo cual sería meramente un “lavado de manos” discursivo y sin un real factor de bienestar para la sociedad herida y las víctimas, o bien puede conseguirse la Reparación sin Verdad (3.2), valiéndose de forma vacía y despiadada de una distribución de recursos y homenajes para “comprar” la paz de las víctimas, sublimando sus exigencias profundas.

Nos quedamos con un comentario de Nelly Richard, destacada académica crítica:

“La inhibición de lo testimonial como voz portadora de una dislocación subjetivo-existencial y la funcionalización del testimonio como simple reserva de información útilmente traspasable al lenguaje burocrático e institucional de las comisiones, informes y tribunales, atenuaron la figuración repulsiva de la memoria de lo abyecto que simbolizaba el pasado de la dictadura, a favor de la memoria inclusiva de la reconciliación que pretendía unir a “todos los chilenos”. ¿Cómo inscribir la problemática del recuerdo en el paisaje nivelado de una transición (mercado y consenso) que declara socialmente inconveniente la preocupación por una memoria de daños que no encuentra dónde grabar sus recuerdos figurados? ¿Cómo desatar los nudos controversiales de la memoria que quedaron trabados por el discurso homogéneo de la reconciliación?” (Richard, 2010, p. 38)

El ejercicio de anonimizar y ocultar los factores humanos dentro de los informes de derechos humanos, en un acto de protección de las identidades de criminales e instituciones participantes, representa, a través del lente de Richard, una forma de suavización de los horrores experimentados: gran necesidad en el proceso de transición a la democracia y reconciliación de la sociedad con sus dominadores. Un proceso de Verdad, Justicia y Reparación propiamente tal requiere superar las relaciones de poder heredadas por de la dictadura, y exigir de una vez por todas que se trate el tema con la crudeza, seriedad, e inmisericordia que se requiere: ¿por qué seguimos tratando con guantes de seda a perpetradores de crímenes de lesa humanidad? 


### Referencias

- Richard, N. (2010). Crítica de la memoria (1990-2010) (pp. 1–271). Ediciones Universidad Diego Portales.
- Universidad Diego Portales, Collins, C., Hau, B., Delgado, J. P., & Hernandez, R. (2014). ¿Una nueva medida de lo posible? Verdad, justicia, memoria y reparaciones posdictadura. In Informe anual sobre derechos humanos en Chile 2014 (pp. 21–62). Santiago: Ediciones Universidad Diego Portales.
- Cámara de diputados de Chile. Modifica ley N° 19.992, para establecer el carácter público de los antecedentes recogidos por la Comisión Nacional sobre Prisión Política y Tortura. (2014). 9598-17.
- Instituto Nacional de Derechos Humanos. (2015). Acceso a la información pública, archivos y acceso a la justicia. In Informe Anual Situación de los Derechos Humanos en Chile 2014 (pp. 273–295).

> Universidad Alberto Hurtado. Centro Ignaciano Universitario. Curso de Formación General Teológica. Iglesia y derechos humanos en Latinoamérica

> Profesor: Boris Hau